In [1]:
import pandas as pd
import os
import numpy as np

In [ ]:
def loadGRKota():
    folder_path = 'data'   
    df = pd.read_csv(os.path.join(folder_path, 'GR Kota Full.csv'))
    return df

def loadGRProvinsi():
    folder_path = 'data'
    dfs = []
    for filename in os.listdir(folder_path):
        if filename.startswith('GR Provinsi'):
            file_path = os.path.join(folder_path, filename)
            df = pd.read_csv(file_path)
            dfs.append(df)
    return dfs

def loadP0Provinsi():
    folder_path = 'data'
    dfs = []
    for filename in os.listdir(folder_path):
        if filename.startswith('P0 Provinsi'):
            file_path = os.path.join(folder_path, filename)
            df = pd.read_csv(file_path)
            dfs.append(df)
    return dfs

In [3]:
dfGRKota = loadGRKota()
dfsGRProvinsi = loadGRProvinsi()
dfsP0Provinsi = loadP0Provinsi()

In [4]:
dfGRKota.head(10)

,Kabupaten Kota,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,GINI RATIO SUMATERA UTARA MENURUT KABUPATEN/KOTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2016,2017.0000,2018.0000,2019.0000,2020.0000,2021.0000,2022.000,2023.000,2024.000
2,Sumatera Utara,0.319,0.3150,0.3176,0.3165,0.3161,0.3145,0.312,0.309,0.297
3,Nias,0.2735,0.2491,0.2645,0.2740,0.2512,0.2452,0.275,0.279,0.247
4,Mandailing Natal,0.27,0.2523,0.2574,0.2623,0.2478,0.2403,0.244,0.249,0.250
5,Tapanuli Selatan,0.2729,0.2528,0.2727,0.2467,0.2022,0.2564,0.209,0.219,0.206
6,Tapanuli Tengah,0.3062,0.3058,0.3174,0.3090,0.3350,0.2917,0.233,0.241,0.234
7,Tapanuli Utara,0.3087,0.3289,0.2819,0.3065,0.2867,0.2766,0.242,0.262,0.242
8,Toba,0.3077,0.2922,0.3279,0.2753,0.2903,0.2719,0.305,0.295,0.348
9,Labuhan Batu,0.3082,0.2792,0.2936,0.2767,0.2715,0.2564,0.278,0.244,0.251

In [5]:
dfsGRProvinsi[0].head(10)

,38 Provinsi,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Gini Ratio Menurut Provinsi dan Daerah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Perkotaan,NaN,NaN,Perdesaan,NaN,NaN,Perkotaan+Perdesaan,NaN,NaN
2,NaN,2018,NaN,NaN,2018,NaN,NaN,2018,NaN,NaN
3,NaN,Semester 1 (Maret),Semester 2 (September),Tahunan,Semester 1 (Maret),Semester 2 (September),Tahunan,Semester 1 (Maret),Semester 2 (September),Tahunan
4,ACEH,0.344,0.338,-,0.285,0.273,-,0.325,0.318,-
5,SUMATERA UTARA,0.335,0.33,-,0.272,0.257,-,0.318,0.311,-
6,SUMATERA BARAT,0.338,0.308,-,0.28,0.262,-,0.321,0.305,-
7,RIAU,0.356,0.379,-,0.288,0.292,-,0.327,0.347,-
8,JAMBI,0.354,0.351,-,0.308,0.295,-,0.334,0.335,-
9,SUMATERA SELATAN,0.381,0.354,-,0.316,0.296,-,0.358,0.341,-

In [6]:
dfsP0Provinsi[0].head(10)

          Daerah   2016   2017   2018
0           ACEH  16.73  16.89  15.97
1       Simeulue  19.93   20.2  19.78
2   Aceh Singkil   21.6  22.11  21.25
3   Aceh Selatan  13.48  14.07  14.01
4  Aceh Tenggara  14.46  14.86  14.29
5     Aceh Timur  15.06  15.25  14.49
6    Aceh Tengah  16.64  16.84  15.58
7     Aceh Barat  20.38  20.28  19.31
8     Aceh Besar  15.55  15.41  14.47
9          Pidie  21.25  21.43  20.47

In [7]:
# create empty dataframe
dataset = pd.DataFrame(columns=['p0', 'gr'])
dataset

Empty DataFrame
Columns: [p0, gr]
Index: []

Cleaning GR Kota

In [8]:
def cleanDfGRKota(df):
    # set second row as header
    df.columns = df.iloc[1]
    # remove first and second row
    df = df[2:]

    df = df.rename(columns={df.columns[0]: 'Wilayah'})
    
    df = df[df['Wilayah'] != 'Sumatera Utara']
    new_columns = []
    for col in df.columns:
        if col != 'Wilayah':
            try:
                new_columns.append(int(col))
            except (ValueError, TypeError):
                new_columns.append(col)
        else:
            new_columns.append(col)
    df.columns = new_columns
        # remove column 2016 and 2017 
    cols_to_drop = [2016, 2017]
    
    if cols_to_drop:
        df = df.drop(columns=cols_to_drop)
    return df

In [9]:
dfGRKota = cleanDfGRKota(dfGRKota)
dfGRKota

                Wilayah    2018    2019    2020    2021   2022   2023   2024
3                  Nias  0.2645  0.2740  0.2512  0.2452  0.275  0.279  0.247
4      Mandailing Natal  0.2574  0.2623  0.2478  0.2403  0.244  0.249  0.250
5      Tapanuli Selatan  0.2727  0.2467  0.2022  0.2564  0.209  0.219  0.206
6       Tapanuli Tengah  0.3174  0.3090  0.3350  0.2917  0.233  0.241  0.234
7        Tapanuli Utara  0.2819  0.3065  0.2867  0.2766  0.242  0.262  0.242
8                  Toba  0.3279  0.2753  0.2903  0.2719  0.305  0.295  0.348
9          Labuhan Batu  0.2936  0.2767  0.2715  0.2564  0.278  0.244  0.251
10               Asahan  0.2912  0.2793  0.2605  0.2441  0.255  0.260  0.248
11           Simalungun  0.2897  0.2738  0.2950  0.2641  0.262  0.295  0.257
12                Dairi  0.2649  0.2873  0.2706  0.2268  0.221  0.241  0.215
13                 Karo  0.2682  0.2642  0.2706  0.2327  0.236  0.240  0.214
14         Deli Serdang  0.2935  0.2732  0.3120  0.2628  0.270  0.295  0.262
15              Langkat  0.2534  0.2660  0.2378  0.2381  0.260  0.257  0.260
16         Nias Selatan  0.3295  0.3186  0.2865  0.2411  0.223  0.261  0.247
17   Humbang Hasundutan  0.2909  0.2893  0.2464  0.3043  0.258  0.256  0.302
18        Pakpak Bharat  0.2393  0.2791  0.2475  0.2421  0.274  0.251  0.262
19              Samosir  0.2846  0.3010  0.3175  0.2735  0.298  0.251  0.238
20      Serdang Bedagai  0.2828  0.2571  0.2620  0.2287  0.240  0.225  0.242
21            Batu Bara  0.2494  0.2773  0.2592  0.2396  0.243  0.255  0.258
22   Padang Lawas Utara  0.2989  0.2702  0.2283  0.2547  0.245  0.241  0.223
23         Padang Lawas  0.2985  0.2313  0.2653  0.2525  0.227  0.225  0.224
24  Labuhanbatu Selatan  0.2427  0.2497  0.1935  0.2317  0.247  0.231  0.212
25     Labuanbatu Utara  0.2819  0.2668  0.2624  0.2431  0.276  0.238  0.239
26           Nias Utara  0.2374  0.2844  0.2506  0.2359  0.239  0.228  0.234
27           Nias Barat  0.2833  0.2578  0.2339  0.2238  0.210  0.208  0.219
28              Sibolga  0.3032  0.2718  0.2912  0.2764  0.346  0.246  0.313
29         Tanjungbalai  0.3320  0.2678  0.2716  0.2477  0.245  0.238  0.236
30      Pematangsiantar  0.3340  0.3298  0.3362  0.3076  0.321  0.329  0.297
31        Tebing Tinggi  0.3396  0.3237  0.3337  0.3440  0.334  0.317  0.335
32                Medan  0.3144  0.3519  0.3199  0.4020  0.399  0.373  0.356
33               Binjai  0.3085  0.3511  0.3244  0.2903  0.302  0.318  0.312
34      Padangsidimpuan  0.3593  0.3098  0.3538  0.3101  0.275  0.267  0.296
35         Gunungsitoli  0.3608  0.3183  0.3223  0.3166  0.303  0.308  0.277

Cleaning GR Provinsi

In [10]:
def cleanDfGRProvinsi(df, nama):
    # Drop first three rows
    df.columns = df.iloc[3]

    # Set the first row as header
    df = df[4:]

    # Replace "-" with NaN
    df = df.replace("-", np.nan)
    
    # Keep only the first and last columns
    
    
    # Rename the columns to 'nama' and 'tahun_all'
    df = df.iloc[:, list(range(1)) + list(range(-3, 0))]
    
    # reset index
    df.iloc[:, 1:] = df.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')
    df = df.rename(columns={df.columns[0]: 'Wilayah'})
    df[nama] = df.iloc[:, [1, 2]].mean(axis=1, skipna=True)
    df = df.iloc[:, [0, -1]]

    new_columns = []
    for col in df.columns:
        if col != 'Wilayah':
            try:
                new_columns.append(int(col))
            except (ValueError, TypeError):
                new_columns.append(col)
        else:
            new_columns.append(col)
    df.columns = new_columns
    return df

In [11]:
years = [str(year) for year in range(2018, 2025)]
dfsGRProvinsi = [cleanDfGRProvinsi(df, nama) for df, nama in zip(dfsGRProvinsi, years)]

C:\Users\USER\AppData\Local\Temp\ipykernel_8828\657684347.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("-", np.nan)
C:\Users\USER\AppData\Local\Temp\ipykernel_8828\657684347.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("-", np.nan)
C:\Users\USER\AppData\Local\Temp\ipykernel_8828\657684347.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("-", np.nan)
C:\Users\USER\AppData\Local\Temp\ipykernel_8828\657684347.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("-", np.nan)
C:\Users\USER\AppData\Local\Temp\ipykernel_8828\657684347.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("-", np.nan)
C:\Users\USER\AppData\Local\Temp\ipykernel_8828\657684347.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("-", np.nan)
C:\Users\USER\AppData\Local\Temp\ipykernel_8828\657684347.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("-", np.nan)

In [12]:
dfGRProvinsi = dfsGRProvinsi[0]

# Loop through the rest and merge one by one
for df in dfsGRProvinsi[1:]:
    dfGRProvinsi = pd.merge(dfGRProvinsi, df, on='Wilayah', how='outer')

In [13]:
dfGRProvinsi

,Wilayah,2018,2019,2020,2021,2022,2023,2024
0,ACEH,0.3215,0.32,0.321,0.3235,0.301,0.296,0.294
1,BALI,0.3705,0.368,0.369,0.3765,0.3625,0.362,0.3545
2,BANTEN,0.376,0.363,0.364,0.364,0.37,0.368,0.356
3,BENGKULU,0.3585,0.3345,0.3285,0.3235,0.315,0.333,0.3425
4,DI YOGYAKARTA,0.4315,0.4255,0.4355,0.4385,0.449,0.449,0.4315
5,DKI JAKARTA,0.392,0.3925,0.3995,0.41,0.4175,0.431,0.427
6,GORONTALO,0.41,0.4085,0.407,0.4085,0.4205,0.417,0.4135
7,INDONESIA,0.3865,0.381,0.383,0.3825,0.3825,0.388,0.38
8,JAMBI,0.3345,0.3225,0.318,0.318,0.3275,0.343,0.318
9,JAWA BARAT,0.406,0.4,0.4005,0.409,0.4145,0.425,0.4245
10,JAWA TENGAH,0.3675,0.3595,0.3605,0.37,0.37,0.369,0.3655
11,JAWA TIMUR,0.375,0.367,0.365,0.369,0.368,0.387,0.3725
12,KALIMANTAN BARAT,0.332,0.3225,0.321,0.314,0.3125,0.321,0.312
13,KALIMANTAN SELATAN,0.342,0.334,0.3415,0.3275,0.313,0.313,0.3
14,KALIMANTAN TENGAH,0.343,0.3355,0.3245,0.3215,0.314,0.317,0.3025
15,KALIMANTAN TIMUR,0.342,0.3325,0.3315,0.3325,0.322,0.322,0.3155
16,KALIMANTAN UTARA,0.3035,0.2935,0.296,0.2885,0.271,0.277,0.2615
17,KEP. BANGKA BELITUNG,0.2765,0.2655,0.2595,0.2515,0.2455,0.245,0.2395
18,KEP. RIAU,0.3345,0.339,0.3365,0.341,0.3335,0.34,0.353
19,LAMPUNG,0.336,0.33,0.3235,0.3185,0.3135,0.324,0.3015
20,MALUKU,0.3345,0.322,0.322,0.315,0.3035,0.288,0.2865
21,MALUKU UTARA,0.332,0.311,0.299,0.289,0.294,0.3,0.306
22,NUSA TENGGARA BARAT,0.3815,0.3765,0.381,0.3825,0.3735,0.375,0.3625
23,NUSA TENGGARA TIMUR,0.355,0.3555,0.355,0.3425,0.337,0.325,0.316
24,PAPUA,0.391,0.3925,0.3935,0.3965,0.3995,0.386,0.3835
25,PAPUA BARAT,0.3925,0.3835,0.379,0.377,0.377,0.37,0.387
26,PAPUA BARAT DAYA,NaN,NaN,NaN,NaN,NaN,NaN,0.3465
27,PAPUA PEGUNUNGAN,NaN,NaN,NaN,NaN,NaN,NaN,0.343
28,PAPUA SELATAN,NaN,NaN,NaN,NaN,NaN,NaN,0.414
29,PAPUA TENGAH,NaN,NaN,NaN,NaN,NaN,NaN,0.368
30,RIAU,0.337,0.3325,0.325,0.3265,0.3245,0.324,0.3065
31,SULAWESI BARAT,0.368,0.365,0.36,0.361,0.3665,0.351,0.342
32,SULAWESI SELATAN,0.3925,0.39,0.3855,0.3795,0.371,0.377,0.3615
33,SULAWESI TENGAH,0.3315,0.3285,0.3235,0.321,0.3065,0.304,0.305
34,SULAWESI TENGGARA,0.4005,0.396,0.3885,0.392,0.3765,0.371,0.3675
35,SULAWESI UTARA,0.383,0.3715,0.369,0.362,0.362,0.37,0.3535
36,SUMATERA BARAT,0.313,0.3065,0.303,0.303,0.296,0.28,0.285
37,SUMATERA SELATAN,0.3495,0.335,0.3385,0.3405,0.3345,0.338,0.332
38,SUMATERA UTARA,0.3145,0.316,0.315,0.3135,0.319,0.309,0.3015

In [14]:
# Combine dfGRProvinsi and dfGRKota
dfGR = pd.concat([dfGRKota, dfGRProvinsi], ignore_index=True)

In [15]:
dfGR

              Wilayah    2018    2019    2020    2021    2022   2023    2024
0                Nias  0.2645   0.274  0.2512  0.2452   0.275  0.279   0.247
1    Mandailing Natal  0.2574  0.2623  0.2478  0.2403   0.244  0.249    0.25
2    Tapanuli Selatan  0.2727  0.2467  0.2022  0.2564   0.209  0.219   0.206
3     Tapanuli Tengah  0.3174   0.309   0.335  0.2917   0.233  0.241   0.234
4      Tapanuli Utara  0.2819  0.3065  0.2867  0.2766   0.242  0.262   0.242
..                ...     ...     ...     ...     ...     ...    ...     ...
67  SULAWESI TENGGARA  0.4005   0.396  0.3885   0.392  0.3765  0.371  0.3675
68     SULAWESI UTARA   0.383  0.3715   0.369   0.362   0.362   0.37  0.3535
69     SUMATERA BARAT   0.313  0.3065   0.303   0.303   0.296   0.28   0.285
70   SUMATERA SELATAN  0.3495   0.335  0.3385  0.3405  0.3345  0.338   0.332
71     SUMATERA UTARA  0.3145   0.316   0.315  0.3135   0.319  0.309  0.3015

[72 rows x 8 columns]

Clean P0Provinsi

In [16]:
dfsP0Provinsi[0]

                 Daerah   2016   2017   2018
0                  ACEH  16.73  16.89  15.97
1              Simeulue  19.93   20.2  19.78
2          Aceh Singkil   21.6  22.11  21.25
3          Aceh Selatan  13.48  14.07  14.01
4         Aceh Tenggara  14.46  14.86  14.29
..                  ...    ...    ...    ...
573            Tolikara      -      -      -
574    Mamberamo Tengah      -      -      -
575              Yalimo      -      -      -
576            Yahukimo      -      -      -
577  Pegunungan Bintang      -      -      -

[578 rows x 4 columns]

In [17]:
def cleanDfP0Provinsi(df):
    # Find the indices of 'SUMATERA UTARA' and 'SUMATERA BARAT'
    df = df.drop_duplicates(subset='Daerah', keep='first')
    start_idx = df[df['Daerah'] == 'SUMATERA UTARA'].index
    end_idx = df[df['Daerah'] == 'SUMATERA BARAT'].index

    # Select rows between "SUMATERA UTARA" and "SUMATERA BARAT" (excluding those two)
    if not start_idx.empty and not end_idx.empty:
        dfDaerahSumut = df.loc[start_idx[0]+1:end_idx[0]-1]  # Exclude start and end rows
    else:
        dfDaerahSumut = df.iloc[0:0]  # Return empty DataFrame if not found

    # Select rows where 'Daerah' is in uppercase (indicating provinces)
    dfProvinsi = df[df['Daerah'].str.isupper()]

    # Combine dfDaerahSumut and dfProvinsi into a single DataFrame
    dfCombined = pd.concat([dfDaerahSumut, dfProvinsi], ignore_index=True)

    new_columns = []
    for col in dfCombined.columns:
        if col != 'Daerah':
            try:
                new_columns.append(int(col))
            except (ValueError, TypeError):
                new_columns.append(col)
        else:
            new_columns.append(col)

    dfCombined.columns = new_columns
    cols_to_drop = [2016, 2017]
    
    if cols_to_drop[0] in dfCombined.columns or cols_to_drop[1] in dfCombined.columns:
        dfCombined = dfCombined.drop(columns=cols_to_drop)
    return dfCombined

In [18]:
dfsP0Provinsi = [cleanDfP0Provinsi(df) for df in dfsP0Provinsi]

In [19]:
dfsP0Provinsi[0]

              Daerah   2018
0               Nias  16.37
1   Mandailing Natal   9.58
2   Tapanuli Selatan   9.16
3    Tapanuli Tengah  13.17
4     Tapanuli Utara   9.75
..               ...    ...
66  PAPUA BARAT DAYA      -
67             PAPUA  27.74
68     PAPUA SELATAN      -
69      PAPUA TENGAH      -
70  PAPUA PEGUNUNGAN      -

[71 rows x 2 columns]

In [20]:
dfP0 = dfsP0Provinsi[0]

# Loop through the rest and merge one by one
for df in dfsP0Provinsi[1:]:
    dfP0 = pd.merge(dfP0, df, on='Daerah', how='outer')

In [21]:
dfP0.sort_values(by='Daerah', inplace=True)
print(dfP0.to_string())

                   Daerah   2018   2019   2020   2021   2022   2023   2024
0                    ACEH  15.97  15.32  14.99  15.33  14.64  14.45  14.23
1                  Asahan  10.25   9.68   9.04   9.35   8.64   8.21   8.12
2                    BALI   4.01   3.79   3.78   4.53   4.57   4.25      4
3                  BANTEN   5.24   5.09   5.92   6.66   6.16   6.17   5.84
4                BENGKULU  15.43  15.23  15.03  15.22  14.62  14.04  13.56
5               Batu Bara  12.57  12.14  11.88  12.38  11.53  11.38  10.94
6          D I YOGYAKARTA  12.13   11.7  12.28   12.8  11.34  11.04  10.83
7             DKI JAKARTA   3.57   3.47   4.53   4.72   4.69   4.44    4.3
8                   Dairi    8.2    7.7   8.04   8.31   7.88   7.47    7.1
9            Deli Serdang   4.13   3.89   3.88   4.01   3.62   3.44   3.44
10              GORONTALO  16.81  15.52  15.22  15.61  15.42  15.15  14.57
11     Humbang Hasundutan      9   8.75   9.36   9.65   8.86   8.69   8.44
12                  JAMBI   7.92    7.6   7.58   8.09   7.62   7.58    7.1
13             JAWA BARAT   7.45   6.91   7.88    8.4   8.06   7.62   7.46
14            JAWA TENGAH  11.32   10.8  11.41  11.79  10.93  10.77  10.47
15             JAWA TIMUR  10.98  10.37  11.09   11.4  10.38  10.35   9.79
16       KALIMANTAN BARAT   7.77   7.49   7.17   7.15   6.73   6.71   6.32
17     KALIMANTAN SELATAN   4.54   4.55   4.38   4.83   4.49   4.29   4.11
18      KALIMANTAN TENGAH   5.17   4.98   4.82   5.16   5.28   5.11   5.17
19       KALIMANTAN TIMUR   6.03   5.94    6.1   6.54   6.31   6.11   5.78
20       KALIMANTAN UTARA   7.09   6.63    6.8   7.36   6.77   6.45   6.32
21   KEP. BANGKA BELITUNG   5.25   4.62   4.53    4.9   4.45   4.52   4.55
22         KEPULAUAN RIAU    6.2    5.9   5.92   6.12   6.24   5.69   5.37
23                   Karo   8.67   8.23    8.7   8.79   8.17   7.98   7.37
24            Kota Binjai   5.88   5.66   5.71   5.81    5.1   4.79   4.75
25      Kota Gunungsitoli  18.44  16.23  16.41  16.45  14.81  14.78  14.72
26             Kota Medan   8.25   8.08   8.01   8.34   8.07      8   7.94
27   Kota Padangsidimpuan   7.69   7.26    7.4   7.53   6.89   6.85   6.23
28  Kota Pematang Siantar    8.7   8.63   8.27   8.52   7.88   7.24    7.2
29           Kota Sibolga  12.38  12.36  11.95  12.33  11.47  11.42  11.39
30     Kota Tanjung Balai  14.64  14.04  13.33   13.4  12.45  12.21  11.97
31     Kota Tebing Tinggi  10.27   9.94   9.85   10.3   9.59   9.49   8.79
32                LAMPUNG  13.14  12.62  12.34  12.62  11.57  11.11  10.69
33           Labuhan Batu   8.61   8.44   8.44   8.74   8.26   7.99   7.84
34   Labuhan Batu Selatan     10   8.94   8.34   8.53   8.09   8.06   7.73
35     Labuhan Batu Utara  10.12   9.57   9.53  10.02   9.09   9.08   8.98
36                Langkat   10.2   9.91   9.73  10.12   9.49   9.23   9.04
37                 MALUKU  18.12  17.69  17.44  17.87  15.97  16.42  16.05
38           MALUKU UTARA   6.64   6.77   6.78   6.89   6.23   6.46   6.32
39       Mandailing Natal   9.58   9.11   9.18   9.49   8.92   8.86   8.69
40    NUSA TENGGARA BARAT  14.75  14.56  13.97  14.14  13.68  13.85  12.91
41    NUSA TENGGARA TIMUR  21.35  21.09   20.9  20.99  20.05  19.96  19.48
42                   Nias  16.37  15.94   16.6  16.82     16   15.1  14.89
43             Nias Barat  26.72  25.51  25.69  26.42  24.75  22.81  22.68
44           Nias Selatan  16.65  16.45  16.74  16.92  16.48  16.39  16.32
45             Nias Utara  26.56  24.99  25.07  25.66   23.4  21.79   21.5
46                  PAPUA  27.74  27.53  26.64  26.86  26.56  26.03  17.26
47            PAPUA BARAT  23.01  22.17  21.37  21.84  21.33  20.49  21.66
48       PAPUA BARAT DAYA      -      -      -      -      -      -  18.13
49       PAPUA PEGUNUNGAN      -      -      -      -      -      -  32.97
50          PAPUA SELATAN      -      -      -      -      -      -  17.44
51           PAPUA TENGAH      -      -      -      -      -      -  29.76
52           Padang Lawas   8.41   8.28   8.37   8.69   8.05   7.89   7.87
53     Padang Lawas Utara  10.06    9.6    9.7   9.92   8.94   8.79   8.97
54          Pakpak Bharat   9.74   9.27   9.28   9.35   8.66   7.54   6.87
55                   RIAU   7.39   7.08   6.82   7.12   6.78   6.68   6.67
56         SULAWESI BARAT  11.25  11.02  10.87  11.29  11.75  11.49  11.21
57       SULAWESI SELATAN   9.06   8.69   8.72   8.78   8.63    8.7   8.06
58        SULAWESI TENGAH  14.01  13.48  12.92     13  12.33  12.41  11.77
59      SULAWESI TENGGARA  11.63  11.24     11  11.66  11.17  11.43  11.21
60         SULAWESI UTARA    7.8   7.66   7.62   7.77   7.28   7.38   7.25
61         SUMATERA BARAT   6.65   6.42   6.28   6.63   5.92   5.95   5.97
62       SUMATERA SELATAN   12.8  12.71  12.66  12.84   11.9  11.78  10.97
63         SUMATERA UTARA   9.22   8.83   8.75   9.01   8.42   8.15   7.99
64                Samosir  13.38  12.52  12.48  12.68  11.77  11.66  11.63
65        Serdang Bedagai   8.22    7.9   7.97    8.3   7.82   7.44   6.97
66             Simalungun   9.31   8.81   8.46   8.81   8.26   7.87   7.72
67       Tapanuli Selatan   9.16    8.6   8.47    8.8   8.07   7.01   6.92
68        Tapanuli Tengah  13.17  12.53  12.38  12.67  11.71   11.5   11.8
69         Tapanuli Utara   9.75   9.48   9.37   9.72   8.93   8.54   8.21
70           Toba Samosir   8.67    8.6   8.71   8.99   8.89   8.04   8.07

In [22]:
dfGR.sort_values(by='Wilayah', inplace=True)
print(dfGR.to_string())

                 Wilayah    2018    2019    2020    2021    2022   2023    2024
33                  ACEH  0.3215    0.32   0.321  0.3235   0.301  0.296   0.294
7                 Asahan  0.2912  0.2793  0.2605  0.2441   0.255   0.26   0.248
34                  BALI  0.3705   0.368   0.369  0.3765  0.3625  0.362  0.3545
35                BANTEN   0.376   0.363   0.364   0.364    0.37  0.368   0.356
36              BENGKULU  0.3585  0.3345  0.3285  0.3235   0.315  0.333  0.3425
18             Batu Bara  0.2494  0.2773  0.2592  0.2396   0.243  0.255   0.258
30                Binjai  0.3085  0.3511  0.3244  0.2903   0.302  0.318   0.312
37         DI YOGYAKARTA  0.4315  0.4255  0.4355  0.4385   0.449  0.449  0.4315
38           DKI JAKARTA   0.392  0.3925  0.3995    0.41  0.4175  0.431   0.427
9                  Dairi  0.2649  0.2873  0.2706  0.2268   0.221  0.241   0.215
11          Deli Serdang  0.2935  0.2732   0.312  0.2628    0.27  0.295   0.262
39             GORONTALO    0.41  0.4085   0.407  0.4085  0.4205  0.417  0.4135
32          Gunungsitoli  0.3608  0.3183  0.3223  0.3166   0.303  0.308   0.277
14    Humbang Hasundutan  0.2909  0.2893  0.2464  0.3043   0.258  0.256   0.302
40             INDONESIA  0.3865   0.381   0.383  0.3825  0.3825  0.388    0.38
41                 JAMBI  0.3345  0.3225   0.318   0.318  0.3275  0.343   0.318
42            JAWA BARAT   0.406     0.4  0.4005   0.409  0.4145  0.425  0.4245
43           JAWA TENGAH  0.3675  0.3595  0.3605    0.37    0.37  0.369  0.3655
44            JAWA TIMUR   0.375   0.367   0.365   0.369   0.368  0.387  0.3725
45      KALIMANTAN BARAT   0.332  0.3225   0.321   0.314  0.3125  0.321   0.312
46    KALIMANTAN SELATAN   0.342   0.334  0.3415  0.3275   0.313  0.313     0.3
47     KALIMANTAN TENGAH   0.343  0.3355  0.3245  0.3215   0.314  0.317  0.3025
48      KALIMANTAN TIMUR   0.342  0.3325  0.3315  0.3325   0.322  0.322  0.3155
49      KALIMANTAN UTARA  0.3035  0.2935   0.296  0.2885   0.271  0.277  0.2615
50  KEP. BANGKA BELITUNG  0.2765  0.2655  0.2595  0.2515  0.2455  0.245  0.2395
51             KEP. RIAU  0.3345   0.339  0.3365   0.341  0.3335   0.34   0.353
10                  Karo  0.2682  0.2642  0.2706  0.2327   0.236   0.24   0.214
52               LAMPUNG   0.336    0.33  0.3235  0.3185  0.3135  0.324  0.3015
22      Labuanbatu Utara  0.2819  0.2668  0.2624  0.2431   0.276  0.238   0.239
6           Labuhan Batu  0.2936  0.2767  0.2715  0.2564   0.278  0.244   0.251
21   Labuhanbatu Selatan  0.2427  0.2497  0.1935  0.2317   0.247  0.231   0.212
12               Langkat  0.2534   0.266  0.2378  0.2381    0.26  0.257    0.26
53                MALUKU  0.3345   0.322   0.322   0.315  0.3035  0.288  0.2865
54          MALUKU UTARA   0.332   0.311   0.299   0.289   0.294    0.3   0.306
1       Mandailing Natal  0.2574  0.2623  0.2478  0.2403   0.244  0.249    0.25
29                 Medan  0.3144  0.3519  0.3199   0.402   0.399  0.373   0.356
55   NUSA TENGGARA BARAT  0.3815  0.3765   0.381  0.3825  0.3735  0.375  0.3625
56   NUSA TENGGARA TIMUR   0.355  0.3555   0.355  0.3425   0.337  0.325   0.316
0                   Nias  0.2645   0.274  0.2512  0.2452   0.275  0.279   0.247
24            Nias Barat  0.2833  0.2578  0.2339  0.2238    0.21  0.208   0.219
13          Nias Selatan  0.3295  0.3186  0.2865  0.2411   0.223  0.261   0.247
23            Nias Utara  0.2374  0.2844  0.2506  0.2359   0.239  0.228   0.234
57                 PAPUA   0.391  0.3925  0.3935  0.3965  0.3995  0.386  0.3835
58           PAPUA BARAT  0.3925  0.3835   0.379   0.377   0.377   0.37   0.387
59      PAPUA BARAT DAYA     NaN     NaN     NaN     NaN     NaN    NaN  0.3465
60      PAPUA PEGUNUNGAN     NaN     NaN     NaN     NaN     NaN    NaN   0.343
61         PAPUA SELATAN     NaN     NaN     NaN     NaN     NaN    NaN   0.414
62          PAPUA TENGAH     NaN     NaN     NaN     NaN     NaN    NaN   0.368
20          Padang Lawas  0.2985  0.2313  0.2653  0.2525   0.227  0.225   0.224
19    Padang Lawas Utara  0.2989  0.2702  0.2283  0.2547   0.245  0.241   0.223
31       Padangsidimpuan  0.3593  0.3098  0.3538  0.3101   0.275  0.267   0.296
15         Pakpak Bharat  0.2393  0.2791  0.2475  0.2421   0.274  0.251   0.262
27       Pematangsiantar   0.334  0.3298  0.3362  0.3076   0.321  0.329   0.297
63                  RIAU   0.337  0.3325   0.325  0.3265  0.3245  0.324  0.3065
64        SULAWESI BARAT   0.368   0.365    0.36   0.361  0.3665  0.351   0.342
65      SULAWESI SELATAN  0.3925    0.39  0.3855  0.3795   0.371  0.377  0.3615
66       SULAWESI TENGAH  0.3315  0.3285  0.3235   0.321  0.3065  0.304   0.305
67     SULAWESI TENGGARA  0.4005   0.396  0.3885   0.392  0.3765  0.371  0.3675
68        SULAWESI UTARA   0.383  0.3715   0.369   0.362   0.362   0.37  0.3535
69        SUMATERA BARAT   0.313  0.3065   0.303   0.303   0.296   0.28   0.285
70      SUMATERA SELATAN  0.3495   0.335  0.3385  0.3405  0.3345  0.338   0.332
71        SUMATERA UTARA  0.3145   0.316   0.315  0.3135   0.319  0.309  0.3015
16               Samosir  0.2846   0.301  0.3175  0.2735   0.298  0.251   0.238
17       Serdang Bedagai  0.2828  0.2571   0.262  0.2287    0.24  0.225   0.242
25               Sibolga  0.3032  0.2718  0.2912  0.2764   0.346  0.246   0.313
8             Simalungun  0.2897  0.2738   0.295  0.2641   0.262  0.295   0.257
26          Tanjungbalai   0.332  0.2678  0.2716  0.2477   0.245  0.238   0.236
2       Tapanuli Selatan  0.2727  0.2467  0.2022  0.2564   0.209  0.219   0.206
3        Tapanuli Tengah  0.3174   0.309   0.335  0.2917   0.233  0.241   0.234
4         Tapanuli Utara  0.2819  0.3065  0.2867  0.2766   0.242  0.262   0.242
28         Tebing Tinggi  0.3396  0.3237  0.3337   0.344   0.334  0.317   0.335
5                   Toba  0.3279  0.2753  0.2903  0.2719   0.305  0.295   0.348

In [23]:
dfNama = pd.merge(dfP0['Daerah'], dfGR['Wilayah'], left_on='Daerah', right_on='Wilayah', how='outer')


#print NaN values in dfNama
print(dfNama[dfNama.isna().any(axis=1)].to_string())

                   Daerah              Wilayah
6                     NaN               Binjai
7          D I YOGYAKARTA                  NaN
8                     NaN        DI YOGYAKARTA
13                    NaN         Gunungsitoli
15                    NaN            INDONESIA
26                    NaN            KEP. RIAU
27         KEPULAUAN RIAU                  NaN
29            Kota Binjai                  NaN
30      Kota Gunungsitoli                  NaN
31             Kota Medan                  NaN
32   Kota Padangsidimpuan                  NaN
33  Kota Pematang Siantar                  NaN
34           Kota Sibolga                  NaN
35     Kota Tanjung Balai                  NaN
36     Kota Tebing Tinggi                  NaN
38                    NaN     Labuanbatu Utara
40   Labuhan Batu Selatan                  NaN
41     Labuhan Batu Utara                  NaN
42                    NaN  Labuhanbatu Selatan
47                    NaN                Medan
62                    NaN      Padangsidimpuan
64                    NaN      Pematangsiantar
76                    NaN              Sibolga
78                    NaN         Tanjungbalai
82                    NaN        Tebing Tinggi
83                    NaN                 Toba
84           Toba Samosir                  NaN

In [24]:
def replaceWords(df, column, old_word, new_word):
    # Replace old_word with new_word in the 'Daerah' column
    df[column] = df[column].str.replace(old_word, new_word, regex=False)
    return df

In [25]:
dfP0 = replaceWords(dfP0, 'Daerah', 'Kota ', '')
dfP0 = replaceWords(dfP0, 'Daerah', 'D I YOGYAKARTA', 'DI YOGYAKARTA')
dfGR = replaceWords(dfGR, 'Wilayah', 'KEP.', 'KEPULAUAN')
dfP0 = replaceWords(dfP0, 'Daerah', 'KEP.', 'KEPULAUAN')
dfGR = replaceWords(dfGR, 'Wilayah', 'Labuanbatu ', 'Labuhan Batu ')
dfGR = replaceWords(dfGR, 'Wilayah', 'Labuhanbatu ', 'Labuhan Batu ')
dfGR = replaceWords(dfGR, 'Wilayah', 'Pematangsiantar', 'Pematang Siantar')
dfGR = replaceWords(dfGR, 'Wilayah', 'Tanjungbalai', 'Tanjung Balai')
dfP0 = replaceWords(dfP0, 'Daerah', ' Samosir', '')
dfGR = dfGR[~dfGR['Wilayah'].str.contains('INDONESIA', na=False)]

In [26]:
dfNama = pd.merge(dfP0['Daerah'], dfGR['Wilayah'], left_on='Daerah', right_on='Wilayah', how='outer')


#print NaN values in dfNama
print(dfNama[dfNama.isna().any(axis=1)].to_string())

Empty DataFrame
Columns: [Daerah, Wilayah]
Index: []

In [27]:
# Check rows with NaN values in dfP0
print(dfP0[dfP0.isna().any(axis=1)].to_string())

Empty DataFrame
Columns: [Daerah, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Index: []

In [28]:
# Check rows with NaN values in dfGR
print(dfGR[dfGR.isna().any(axis=1)].to_string())

             Wilayah 2018 2019 2020 2021 2022 2023    2024
59  PAPUA BARAT DAYA  NaN  NaN  NaN  NaN  NaN  NaN  0.3465
60  PAPUA PEGUNUNGAN  NaN  NaN  NaN  NaN  NaN  NaN   0.343
61     PAPUA SELATAN  NaN  NaN  NaN  NaN  NaN  NaN   0.414
62      PAPUA TENGAH  NaN  NaN  NaN  NaN  NaN  NaN   0.368

In [29]:
# Remove any rows with PAPUA in the 'Daerah' column from dfP0 and 'Wilayah' column from dfGR
dfP0 = dfP0[~dfP0['Daerah'].str.contains('PAPUA', na=False)]
dfGR = dfGR[~dfGR['Wilayah'].str.contains('PAPUA', na=False)]

In [30]:
print(dfGR[dfGR.isna().any(axis=1)].to_string())

Empty DataFrame
Columns: [Wilayah, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Index: []

In [31]:
# Melt the dfGR DataFrame to long format
dfGR_melted = dfGR.melt(id_vars=['Wilayah'], var_name='Tahun', value_name='GR')
dfP0_melted = dfP0.melt(id_vars=['Daerah'], var_name='Tahun', value_name='P0')
dfGR_melted = dfGR_melted.rename(columns={'Wilayah': 'Daerah'})

In [32]:
# sort by Tahun, and  then by Wilayah
dfGR_melted.sort_values(by=['Tahun', 'Daerah'], inplace=True)
dfP0_melted.sort_values(by=['Tahun', 'Daerah'], inplace=True)

In [33]:
print(dfGR_melted.to_string())

                        Daerah Tahun      GR
0                         ACEH  2018  0.3215
1                       Asahan  2018  0.2912
2                         BALI  2018  0.3705
3                       BANTEN  2018   0.376
4                     BENGKULU  2018  0.3585
5                    Batu Bara  2018  0.2494
6                       Binjai  2018  0.3085
7                DI YOGYAKARTA  2018  0.4315
8                  DKI JAKARTA  2018   0.392
9                        Dairi  2018  0.2649
10                Deli Serdang  2018  0.2935
11                   GORONTALO  2018    0.41
12                Gunungsitoli  2018  0.3608
13          Humbang Hasundutan  2018  0.2909
14                       JAMBI  2018  0.3345
15                  JAWA BARAT  2018   0.406
16                 JAWA TENGAH  2018  0.3675
17                  JAWA TIMUR  2018   0.375
18            KALIMANTAN BARAT  2018   0.332
19          KALIMANTAN SELATAN  2018   0.342
20           KALIMANTAN TENGAH  2018   0.343
21            KALIMANTAN TIMUR  2018   0.342
22            KALIMANTAN UTARA  2018  0.3035
23   KEPULAUAN BANGKA BELITUNG  2018  0.2765
24              KEPULAUAN RIAU  2018  0.3345
25                        Karo  2018  0.2682
26                     LAMPUNG  2018   0.336
28                Labuhan Batu  2018  0.2936
29        Labuhan Batu Selatan  2018  0.2427
27          Labuhan Batu Utara  2018  0.2819
30                     Langkat  2018  0.2534
31                      MALUKU  2018  0.3345
32                MALUKU UTARA  2018   0.332
33            Mandailing Natal  2018  0.2574
34                       Medan  2018  0.3144
35         NUSA TENGGARA BARAT  2018  0.3815
36         NUSA TENGGARA TIMUR  2018   0.355
37                        Nias  2018  0.2645
38                  Nias Barat  2018  0.2833
39                Nias Selatan  2018  0.3295
40                  Nias Utara  2018  0.2374
41                Padang Lawas  2018  0.2985
42          Padang Lawas Utara  2018  0.2989
43             Padangsidimpuan  2018  0.3593
44               Pakpak Bharat  2018  0.2393
45            Pematang Siantar  2018   0.334
46                        RIAU  2018   0.337
47              SULAWESI BARAT  2018   0.368
48            SULAWESI SELATAN  2018  0.3925
49             SULAWESI TENGAH  2018  0.3315
50           SULAWESI TENGGARA  2018  0.4005
51              SULAWESI UTARA  2018   0.383
52              SUMATERA BARAT  2018   0.313
53            SUMATERA SELATAN  2018  0.3495
54              SUMATERA UTARA  2018  0.3145
55                     Samosir  2018  0.2846
56             Serdang Bedagai  2018  0.2828
57                     Sibolga  2018  0.3032
58                  Simalungun  2018  0.2897
59               Tanjung Balai  2018   0.332
60            Tapanuli Selatan  2018  0.2727
61             Tapanuli Tengah  2018  0.3174
62              Tapanuli Utara  2018  0.2819
63               Tebing Tinggi  2018  0.3396
64                        Toba  2018  0.3279
65                        ACEH  2019    0.32
66                      Asahan  2019  0.2793
67                        BALI  2019   0.368
68                      BANTEN  2019   0.363
69                    BENGKULU  2019  0.3345
70                   Batu Bara  2019  0.2773
71                      Binjai  2019  0.3511
72               DI YOGYAKARTA  2019  0.4255
73                 DKI JAKARTA  2019  0.3925
74                       Dairi  2019  0.2873
75                Deli Serdang  2019  0.2732
76                   GORONTALO  2019  0.4085
77                Gunungsitoli  2019  0.3183
78          Humbang Hasundutan  2019  0.2893
79                       JAMBI  2019  0.3225
80                  JAWA BARAT  2019     0.4
81                 JAWA TENGAH  2019  0.3595
82                  JAWA TIMUR  2019   0.367
83            KALIMANTAN BARAT  2019  0.3225
84          KALIMANTAN SELATAN  2019   0.334
85           KALIMANTAN TENGAH  2019  0.3355
86            KALIMANTAN TIMUR  2019  0.3325
87            KALIMANTAN UTARA  2019  0.2935
88   KEPULAUAN BANGKA BELITUNG  2019  0.2655
89              KEPULAUAN RIAU  2019   0.339
90                        Karo  2019  0.2642
91                     LAMPUNG  2019    0.33
93                Labuhan Batu  2019  0.2767
94        Labuhan Batu Selatan  2019  0.2497
92          Labuhan Batu Utara  2019  0.2668
95                     Langkat  2019   0.266
96                      MALUKU  2019   0.322
97                MALUKU UTARA  2019   0.311
98            Mandailing Natal  2019  0.2623
99                       Medan  2019  0.3519
100        NUSA TENGGARA BARAT  2019  0.3765
101        NUSA TENGGARA TIMUR  2019  0.3555
102                       Nias  2019   0.274
103                 Nias Barat  2019  0.2578
104               Nias Selatan  2019  0.3186
105                 Nias Utara  2019  0.2844
106               Padang Lawas  2019  0.2313
107         Padang Lawas Utara  2019  0.2702
108            Padangsidimpuan  2019  0.3098
109              Pakpak Bharat  2019  0.2791
110           Pematang Siantar  2019  0.3298
111                       RIAU  2019  0.3325
112             SULAWESI BARAT  2019   0.365
113           SULAWESI SELATAN  2019    0.39
114            SULAWESI TENGAH  2019  0.3285
115          SULAWESI TENGGARA  2019   0.396
116             SULAWESI UTARA  2019  0.3715
117             SUMATERA BARAT  2019  0.3065
118           SUMATERA SELATAN  2019   0.335
119             SUMATERA UTARA  2019   0.316
120                    Samosir  2019   0.301
121            Serdang Bedagai  2019  0.2571
122                    Sibolga  2019  0.2718
123                 Simalungun  2019  0.2738
124              Tanjung Balai  2019  0.2678
125           Tapanuli Selatan  2019  0.2467
126            Tapanuli Tengah  2019   0.309
127             Tapanuli Utara  2019  0.3065
128              Tebing Tinggi  2019  0.3237
129                       Toba  2019  0.2753
130                       ACEH  2020   0.321
131                     Asahan  2020  0.2605
132                       BALI  2020   0.369
133                     BANTEN  2020   0.364
134                   BENGKULU  2020  0.3285
135                  Batu Bara  2020  0.2592
136                     Binjai  2020  0.3244
137              DI YOGYAKARTA  2020  0.4355
138                DKI JAKARTA  2020  0.3995
139                      Dairi  2020  0.2706
140               Deli Serdang  2020   0.312
141                  GORONTALO  2020   0.407
142               Gunungsitoli  2020  0.3223
143         Humbang Hasundutan  2020  0.2464
144                      JAMBI  2020   0.318
145                 JAWA BARAT  2020  0.4005
146                JAWA TENGAH  2020  0.3605
147                 JAWA TIMUR  2020   0.365
148           KALIMANTAN BARAT  2020   0.321
149         KALIMANTAN SELATAN  2020  0.3415
150          KALIMANTAN TENGAH  2020  0.3245
151           KALIMANTAN TIMUR  2020  0.3315
152           KALIMANTAN UTARA  2020   0.296
153  KEPULAUAN BANGKA BELITUNG  2020  0.2595
154             KEPULAUAN RIAU  2020  0.3365
155                       Karo  2020  0.2706
156                    LAMPUNG  2020  0.3235
158               Labuhan Batu  2020  0.2715
159       Labuhan Batu Selatan  2020  0.1935
157         Labuhan Batu Utara  2020  0.2624
160                    Langkat  2020  0.2378
161                     MALUKU  2020   0.322
162               MALUKU UTARA  2020   0.299
163           Mandailing Natal  2020  0.2478
164                      Medan  2020  0.3199
165        NUSA TENGGARA BARAT  2020   0.381
166        NUSA TENGGARA TIMUR  2020   0.355
167                       Nias  2020  0.2512
168                 Nias Barat  2020  0.2339
169               Nias Selatan  2020  0.2865
170                 Nias Utara  2020  0.2506
171               Padang Lawas  2020  0.2653
172         Padang Lawas Utara  2020  0.2283
173            Padangsidimpuan  2020  0.3538
174              Pakpak Bharat  2020  0.2475
175           Pematang Siantar  2020  0.3362
176                       RIAU  2020   0.325
177             SULAWESI BARAT  2020    0.36
178           SULAWESI SELATAN  2020  0.3855
179            SULAWESI TENGAH  2020  0.3235
180          SULAWESI TENGGARA  2020  0.3885
181             SULAWESI UTARA  2020   0.369
182             SUMATERA BARAT  2020   0.303
183           SUMATERA SELATAN  2020  0.3385
184             SUMATERA UTARA  2020   0.315
185                    Samosir  2020  0.3175
186            Serdang Bedagai  2020   0.262
187                    Sibolga  2020  0.2912
188                 Simalungun  2020   0.295
189              Tanjung Balai  2020  0.2716
190           Tapanuli Selatan  2020  0.2022
191            Tapanuli Tengah  2020   0.335
192             Tapanuli Utara  2020  0.2867
193              Tebing Tinggi  2020  0.3337
194                       Toba  2020  0.2903
195                       ACEH  2021  0.3235
196                     Asahan  2021  0.2441
197                       BALI  2021  0.3765
198                     BANTEN  2021   0.364
199                   BENGKULU  2021  0.3235
200                  Batu Bara  2021  0.2396
201                     Binjai  2021  0.2903
202              DI YOGYAKARTA  2021  0.4385
203                DKI JAKARTA  2021    0.41
204                      Dairi  2021  0.2268
205               Deli Serdang  2021  0.2628
206                  GORONTALO  2021  0.4085
207               Gunungsitoli  2021  0.3166
208         Humbang Hasundutan  2021  0.3043
209                      JAMBI  2021   0.318
210                 JAWA BARAT  2021   0.409
211                JAWA TENGAH  2021    0.37
212                 JAWA TIMUR  2021   0.369
213           KALIMANTAN BARAT  2021   0.314
214         KALIMANTAN SELATAN  2021  0.3275
215          KALIMANTAN TENGAH  2021  0.3215
216           KALIMANTAN TIMUR  2021  0.3325
217           KALIMANTAN UTARA  2021  0.2885
218  KEPULAUAN BANGKA BELITUNG  2021  0.2515
219             KEPULAUAN RIAU  2021   0.341
220                       Karo  2021  0.2327
221                    LAMPUNG  2021  0.3185
223               Labuhan Batu  2021  0.2564
224       Labuhan Batu Selatan  2021  0.2317
222         Labuhan Batu Utara  2021  0.2431
225                    Langkat  2021  0.2381
226                     MALUKU  2021   0.315
227               MALUKU UTARA  2021   0.289
228           Mandailing Natal  2021  0.2403
229                      Medan  2021   0.402
230        NUSA TENGGARA BARAT  2021  0.3825
231        NUSA TENGGARA TIMUR  2021  0.3425
232                       Nias  2021  0.2452
233                 Nias Barat  2021  0.2238
234               Nias Selatan  2021  0.2411
235                 Nias Utara  2021  0.2359
236               Padang Lawas  2021  0.2525
237         Padang Lawas Utara  2021  0.2547
238            Padangsidimpuan  2021  0.3101
239              Pakpak Bharat  2021  0.2421
240           Pematang Siantar  2021  0.3076
241                       RIAU  2021  0.3265
242             SULAWESI BARAT  2021   0.361
243           SULAWESI SELATAN  2021  0.3795
244            SULAWESI TENGAH  2021   0.321
245          SULAWESI TENGGARA  2021   0.392
246             SULAWESI UTARA  2021   0.362
247             SUMATERA BARAT  2021   0.303
248           SUMATERA SELATAN  2021  0.3405
249             SUMATERA UTARA  2021  0.3135
250                    Samosir  2021  0.2735
251            Serdang Bedagai  2021  0.2287
252                    Sibolga  2021  0.2764
253                 Simalungun  2021  0.2641
254              Tanjung Balai  2021  0.2477
255           Tapanuli Selatan  2021  0.2564
256            Tapanuli Tengah  2021  0.2917
257             Tapanuli Utara  2021  0.2766
258              Tebing Tinggi  2021   0.344
259                       Toba  2021  0.2719
260                       ACEH  2022   0.301
261                     Asahan  2022   0.255
262                       BALI  2022  0.3625
263                     BANTEN  2022    0.37
264                   BENGKULU  2022   0.315
265                  Batu Bara  2022   0.243
266                     Binjai  2022   0.302
267              DI YOGYAKARTA  2022   0.449
268                DKI JAKARTA  2022  0.4175
269                      Dairi  2022   0.221
270               Deli Serdang  2022    0.27
271                  GORONTALO  2022  0.4205
272               Gunungsitoli  2022   0.303
273         Humbang Hasundutan  2022   0.258
274                      JAMBI  2022  0.3275
275                 JAWA BARAT  2022  0.4145
276                JAWA TENGAH  2022    0.37
277                 JAWA TIMUR  2022   0.368
278           KALIMANTAN BARAT  2022  0.3125
279         KALIMANTAN SELATAN  2022   0.313
280          KALIMANTAN TENGAH  2022   0.314
281           KALIMANTAN TIMUR  2022   0.322
282           KALIMANTAN UTARA  2022   0.271
283  KEPULAUAN BANGKA BELITUNG  2022  0.2455
284             KEPULAUAN RIAU  2022  0.3335
285                       Karo  2022   0.236
286                    LAMPUNG  2022  0.3135
288               Labuhan Batu  2022   0.278
289       Labuhan Batu Selatan  2022   0.247
287         Labuhan Batu Utara  2022   0.276
290                    Langkat  2022    0.26
291                     MALUKU  2022  0.3035
292               MALUKU UTARA  2022   0.294
293           Mandailing Natal  2022   0.244
294                      Medan  2022   0.399
295        NUSA TENGGARA BARAT  2022  0.3735
296        NUSA TENGGARA TIMUR  2022   0.337
297                       Nias  2022   0.275
298                 Nias Barat  2022    0.21
299               Nias Selatan  2022   0.223
300                 Nias Utara  2022   0.239
301               Padang Lawas  2022   0.227
302         Padang Lawas Utara  2022   0.245
303            Padangsidimpuan  2022   0.275
304              Pakpak Bharat  2022   0.274
305           Pematang Siantar  2022   0.321
306                       RIAU  2022  0.3245
307             SULAWESI BARAT  2022  0.3665
308           SULAWESI SELATAN  2022   0.371
309            SULAWESI TENGAH  2022  0.3065
310          SULAWESI TENGGARA  2022  0.3765
311             SULAWESI UTARA  2022   0.362
312             SUMATERA BARAT  2022   0.296
313           SUMATERA SELATAN  2022  0.3345
314             SUMATERA UTARA  2022   0.319
315                    Samosir  2022   0.298
316            Serdang Bedagai  2022    0.24
317                    Sibolga  2022   0.346
318                 Simalungun  2022   0.262
319              Tanjung Balai  2022   0.245
320           Tapanuli Selatan  2022   0.209
321            Tapanuli Tengah  2022   0.233
322             Tapanuli Utara  2022   0.242
323              Tebing Tinggi  2022   0.334
324                       Toba  2022   0.305
325                       ACEH  2023   0.296
326                     Asahan  2023    0.26
327                       BALI  2023   0.362
328                     BANTEN  2023   0.368
329                   BENGKULU  2023   0.333
330                  Batu Bara  2023   0.255
331                     Binjai  2023   0.318
332              DI YOGYAKARTA  2023   0.449
333                DKI JAKARTA  2023   0.431
334                      Dairi  2023   0.241
335               Deli Serdang  2023   0.295
336                  GORONTALO  2023   0.417
337               Gunungsitoli  2023   0.308
338         Humbang Hasundutan  2023   0.256
339                      JAMBI  2023   0.343
340                 JAWA BARAT  2023   0.425
341                JAWA TENGAH  2023   0.369
342                 JAWA TIMUR  2023   0.387
343           KALIMANTAN BARAT  2023   0.321
344         KALIMANTAN SELATAN  2023   0.313
345          KALIMANTAN TENGAH  2023   0.317
346           KALIMANTAN TIMUR  2023   0.322
347           KALIMANTAN UTARA  2023   0.277
348  KEPULAUAN BANGKA BELITUNG  2023   0.245
349             KEPULAUAN RIAU  2023    0.34
350                       Karo  2023    0.24
351                    LAMPUNG  2023   0.324
353               Labuhan Batu  2023   0.244
354       Labuhan Batu Selatan  2023   0.231
352         Labuhan Batu Utara  2023   0.238
355                    Langkat  2023   0.257
356                     MALUKU  2023   0.288
357               MALUKU UTARA  2023     0.3
358           Mandailing Natal  2023   0.249
359                      Medan  2023   0.373
360        NUSA TENGGARA BARAT  2023   0.375
361        NUSA TENGGARA TIMUR  2023   0.325
362                       Nias  2023   0.279
363                 Nias Barat  2023   0.208
364               Nias Selatan  2023   0.261
365                 Nias Utara  2023   0.228
366               Padang Lawas  2023   0.225
367         Padang Lawas Utara  2023   0.241
368            Padangsidimpuan  2023   0.267
369              Pakpak Bharat  2023   0.251
370           Pematang Siantar  2023   0.329
371                       RIAU  2023   0.324
372             SULAWESI BARAT  2023   0.351
373           SULAWESI SELATAN  2023   0.377
374            SULAWESI TENGAH  2023   0.304
375          SULAWESI TENGGARA  2023   0.371
376             SULAWESI UTARA  2023    0.37
377             SUMATERA BARAT  2023    0.28
378           SUMATERA SELATAN  2023   0.338
379             SUMATERA UTARA  2023   0.309
380                    Samosir  2023   0.251
381            Serdang Bedagai  2023   0.225
382                    Sibolga  2023   0.246
383                 Simalungun  2023   0.295
384              Tanjung Balai  2023   0.238
385           Tapanuli Selatan  2023   0.219
386            Tapanuli Tengah  2023   0.241
387             Tapanuli Utara  2023   0.262
388              Tebing Tinggi  2023   0.317
389                       Toba  2023   0.295
390                       ACEH  2024   0.294
391                     Asahan  2024   0.248
392                       BALI  2024  0.3545
393                     BANTEN  2024   0.356
394                   BENGKULU  2024  0.3425
395                  Batu Bara  2024   0.258
396                     Binjai  2024   0.312
397              DI YOGYAKARTA  2024  0.4315
398                DKI JAKARTA  2024   0.427
399                      Dairi  2024   0.215
400               Deli Serdang  2024   0.262
401                  GORONTALO  2024  0.4135
402               Gunungsitoli  2024   0.277
403         Humbang Hasundutan  2024   0.302
404                      JAMBI  2024   0.318
405                 JAWA BARAT  2024  0.4245
406                JAWA TENGAH  2024  0.3655
407                 JAWA TIMUR  2024  0.3725
408           KALIMANTAN BARAT  2024   0.312
409         KALIMANTAN SELATAN  2024     0.3
410          KALIMANTAN TENGAH  2024  0.3025
411           KALIMANTAN TIMUR  2024  0.3155
412           KALIMANTAN UTARA  2024  0.2615
413  KEPULAUAN BANGKA BELITUNG  2024  0.2395
414             KEPULAUAN RIAU  2024   0.353
415                       Karo  2024   0.214
416                    LAMPUNG  2024  0.3015
418               Labuhan Batu  2024   0.251
419       Labuhan Batu Selatan  2024   0.212
417         Labuhan Batu Utara  2024   0.239
420                    Langkat  2024    0.26
421                     MALUKU  2024  0.2865
422               MALUKU UTARA  2024   0.306
423           Mandailing Natal  2024    0.25
424                      Medan  2024   0.356
425        NUSA TENGGARA BARAT  2024  0.3625
426        NUSA TENGGARA TIMUR  2024   0.316
427                       Nias  2024   0.247
428                 Nias Barat  2024   0.219
429               Nias Selatan  2024   0.247
430                 Nias Utara  2024   0.234
431               Padang Lawas  2024   0.224
432         Padang Lawas Utara  2024   0.223
433            Padangsidimpuan  2024   0.296
434              Pakpak Bharat  2024   0.262
435           Pematang Siantar  2024   0.297
436                       RIAU  2024  0.3065
437             SULAWESI BARAT  2024   0.342
438           SULAWESI SELATAN  2024  0.3615
439            SULAWESI TENGAH  2024   0.305
440          SULAWESI TENGGARA  2024  0.3675
441             SULAWESI UTARA  2024  0.3535
442             SUMATERA BARAT  2024   0.285

In [34]:
print(dfP0_melted.to_string())

                        Daerah Tahun     P0
0                         ACEH  2018  15.97
1                       Asahan  2018  10.25
2                         BALI  2018   4.01
3                       BANTEN  2018   5.24
4                     BENGKULU  2018  15.43
5                    Batu Bara  2018  12.57
24                      Binjai  2018   5.88
6                DI YOGYAKARTA  2018  12.13
7                  DKI JAKARTA  2018   3.57
8                        Dairi  2018    8.2
9                 Deli Serdang  2018   4.13
10                   GORONTALO  2018  16.81
25                Gunungsitoli  2018  18.44
11          Humbang Hasundutan  2018      9
12                       JAMBI  2018   7.92
13                  JAWA BARAT  2018   7.45
14                 JAWA TENGAH  2018  11.32
15                  JAWA TIMUR  2018  10.98
16            KALIMANTAN BARAT  2018   7.77
17          KALIMANTAN SELATAN  2018   4.54
18           KALIMANTAN TENGAH  2018   5.17
19            KALIMANTAN TIMUR  2018   6.03
20            KALIMANTAN UTARA  2018   7.09
21   KEPULAUAN BANGKA BELITUNG  2018   5.25
22              KEPULAUAN RIAU  2018    6.2
23                        Karo  2018   8.67
32                     LAMPUNG  2018  13.14
33                Labuhan Batu  2018   8.61
34        Labuhan Batu Selatan  2018     10
35          Labuhan Batu Utara  2018  10.12
36                     Langkat  2018   10.2
37                      MALUKU  2018  18.12
38                MALUKU UTARA  2018   6.64
39            Mandailing Natal  2018   9.58
26                       Medan  2018   8.25
40         NUSA TENGGARA BARAT  2018  14.75
41         NUSA TENGGARA TIMUR  2018  21.35
42                        Nias  2018  16.37
43                  Nias Barat  2018  26.72
44                Nias Selatan  2018  16.65
45                  Nias Utara  2018  26.56
46                Padang Lawas  2018   8.41
47          Padang Lawas Utara  2018  10.06
27             Padangsidimpuan  2018   7.69
48               Pakpak Bharat  2018   9.74
28            Pematang Siantar  2018    8.7
49                        RIAU  2018   7.39
50              SULAWESI BARAT  2018  11.25
51            SULAWESI SELATAN  2018   9.06
52             SULAWESI TENGAH  2018  14.01
53           SULAWESI TENGGARA  2018  11.63
54              SULAWESI UTARA  2018    7.8
55              SUMATERA BARAT  2018   6.65
56            SUMATERA SELATAN  2018   12.8
57              SUMATERA UTARA  2018   9.22
58                     Samosir  2018  13.38
59             Serdang Bedagai  2018   8.22
29                     Sibolga  2018  12.38
60                  Simalungun  2018   9.31
30               Tanjung Balai  2018  14.64
61            Tapanuli Selatan  2018   9.16
62             Tapanuli Tengah  2018  13.17
63              Tapanuli Utara  2018   9.75
31               Tebing Tinggi  2018  10.27
64                        Toba  2018   8.67
65                        ACEH  2019  15.32
66                      Asahan  2019   9.68
67                        BALI  2019   3.79
68                      BANTEN  2019   5.09
69                    BENGKULU  2019  15.23
70                   Batu Bara  2019  12.14
89                      Binjai  2019   5.66
71               DI YOGYAKARTA  2019   11.7
72                 DKI JAKARTA  2019   3.47
73                       Dairi  2019    7.7
74                Deli Serdang  2019   3.89
75                   GORONTALO  2019  15.52
90                Gunungsitoli  2019  16.23
76          Humbang Hasundutan  2019   8.75
77                       JAMBI  2019    7.6
78                  JAWA BARAT  2019   6.91
79                 JAWA TENGAH  2019   10.8
80                  JAWA TIMUR  2019  10.37
81            KALIMANTAN BARAT  2019   7.49
82          KALIMANTAN SELATAN  2019   4.55
83           KALIMANTAN TENGAH  2019   4.98
84            KALIMANTAN TIMUR  2019   5.94
85            KALIMANTAN UTARA  2019   6.63
86   KEPULAUAN BANGKA BELITUNG  2019   4.62
87              KEPULAUAN RIAU  2019    5.9
88                        Karo  2019   8.23
97                     LAMPUNG  2019  12.62
98                Labuhan Batu  2019   8.44
99        Labuhan Batu Selatan  2019   8.94
100         Labuhan Batu Utara  2019   9.57
101                    Langkat  2019   9.91
102                     MALUKU  2019  17.69
103               MALUKU UTARA  2019   6.77
104           Mandailing Natal  2019   9.11
91                       Medan  2019   8.08
105        NUSA TENGGARA BARAT  2019  14.56
106        NUSA TENGGARA TIMUR  2019  21.09
107                       Nias  2019  15.94
108                 Nias Barat  2019  25.51
109               Nias Selatan  2019  16.45
110                 Nias Utara  2019  24.99
111               Padang Lawas  2019   8.28
112         Padang Lawas Utara  2019    9.6
92             Padangsidimpuan  2019   7.26
113              Pakpak Bharat  2019   9.27
93            Pematang Siantar  2019   8.63
114                       RIAU  2019   7.08
115             SULAWESI BARAT  2019  11.02
116           SULAWESI SELATAN  2019   8.69
117            SULAWESI TENGAH  2019  13.48
118          SULAWESI TENGGARA  2019  11.24
119             SULAWESI UTARA  2019   7.66
120             SUMATERA BARAT  2019   6.42
121           SUMATERA SELATAN  2019  12.71
122             SUMATERA UTARA  2019   8.83
123                    Samosir  2019  12.52
124            Serdang Bedagai  2019    7.9
94                     Sibolga  2019  12.36
125                 Simalungun  2019   8.81
95               Tanjung Balai  2019  14.04
126           Tapanuli Selatan  2019    8.6
127            Tapanuli Tengah  2019  12.53
128             Tapanuli Utara  2019   9.48
96               Tebing Tinggi  2019   9.94
129                       Toba  2019    8.6
130                       ACEH  2020  14.99
131                     Asahan  2020   9.04
132                       BALI  2020   3.78
133                     BANTEN  2020   5.92
134                   BENGKULU  2020  15.03
135                  Batu Bara  2020  11.88
154                     Binjai  2020   5.71
136              DI YOGYAKARTA  2020  12.28
137                DKI JAKARTA  2020   4.53
138                      Dairi  2020   8.04
139               Deli Serdang  2020   3.88
140                  GORONTALO  2020  15.22
155               Gunungsitoli  2020  16.41
141         Humbang Hasundutan  2020   9.36
142                      JAMBI  2020   7.58
143                 JAWA BARAT  2020   7.88
144                JAWA TENGAH  2020  11.41
145                 JAWA TIMUR  2020  11.09
146           KALIMANTAN BARAT  2020   7.17
147         KALIMANTAN SELATAN  2020   4.38
148          KALIMANTAN TENGAH  2020   4.82
149           KALIMANTAN TIMUR  2020    6.1
150           KALIMANTAN UTARA  2020    6.8
151  KEPULAUAN BANGKA BELITUNG  2020   4.53
152             KEPULAUAN RIAU  2020   5.92
153                       Karo  2020    8.7
162                    LAMPUNG  2020  12.34
163               Labuhan Batu  2020   8.44
164       Labuhan Batu Selatan  2020   8.34
165         Labuhan Batu Utara  2020   9.53
166                    Langkat  2020   9.73
167                     MALUKU  2020  17.44
168               MALUKU UTARA  2020   6.78
169           Mandailing Natal  2020   9.18
156                      Medan  2020   8.01
170        NUSA TENGGARA BARAT  2020  13.97
171        NUSA TENGGARA TIMUR  2020   20.9
172                       Nias  2020   16.6
173                 Nias Barat  2020  25.69
174               Nias Selatan  2020  16.74
175                 Nias Utara  2020  25.07
176               Padang Lawas  2020   8.37
177         Padang Lawas Utara  2020    9.7
157            Padangsidimpuan  2020    7.4
178              Pakpak Bharat  2020   9.28
158           Pematang Siantar  2020   8.27
179                       RIAU  2020   6.82
180             SULAWESI BARAT  2020  10.87
181           SULAWESI SELATAN  2020   8.72
182            SULAWESI TENGAH  2020  12.92
183          SULAWESI TENGGARA  2020     11
184             SULAWESI UTARA  2020   7.62
185             SUMATERA BARAT  2020   6.28
186           SUMATERA SELATAN  2020  12.66
187             SUMATERA UTARA  2020   8.75
188                    Samosir  2020  12.48
189            Serdang Bedagai  2020   7.97
159                    Sibolga  2020  11.95
190                 Simalungun  2020   8.46
160              Tanjung Balai  2020  13.33
191           Tapanuli Selatan  2020   8.47
192            Tapanuli Tengah  2020  12.38
193             Tapanuli Utara  2020   9.37
161              Tebing Tinggi  2020   9.85
194                       Toba  2020   8.71
195                       ACEH  2021  15.33
196                     Asahan  2021   9.35
197                       BALI  2021   4.53
198                     BANTEN  2021   6.66
199                   BENGKULU  2021  15.22
200                  Batu Bara  2021  12.38
219                     Binjai  2021   5.81
201              DI YOGYAKARTA  2021   12.8
202                DKI JAKARTA  2021   4.72
203                      Dairi  2021   8.31
204               Deli Serdang  2021   4.01
205                  GORONTALO  2021  15.61
220               Gunungsitoli  2021  16.45
206         Humbang Hasundutan  2021   9.65
207                      JAMBI  2021   8.09
208                 JAWA BARAT  2021    8.4
209                JAWA TENGAH  2021  11.79
210                 JAWA TIMUR  2021   11.4
211           KALIMANTAN BARAT  2021   7.15
212         KALIMANTAN SELATAN  2021   4.83
213          KALIMANTAN TENGAH  2021   5.16
214           KALIMANTAN TIMUR  2021   6.54
215           KALIMANTAN UTARA  2021   7.36
216  KEPULAUAN BANGKA BELITUNG  2021    4.9
217             KEPULAUAN RIAU  2021   6.12
218                       Karo  2021   8.79
227                    LAMPUNG  2021  12.62
228               Labuhan Batu  2021   8.74
229       Labuhan Batu Selatan  2021   8.53
230         Labuhan Batu Utara  2021  10.02
231                    Langkat  2021  10.12
232                     MALUKU  2021  17.87
233               MALUKU UTARA  2021   6.89
234           Mandailing Natal  2021   9.49
221                      Medan  2021   8.34
235        NUSA TENGGARA BARAT  2021  14.14
236        NUSA TENGGARA TIMUR  2021  20.99
237                       Nias  2021  16.82
238                 Nias Barat  2021  26.42
239               Nias Selatan  2021  16.92
240                 Nias Utara  2021  25.66
241               Padang Lawas  2021   8.69
242         Padang Lawas Utara  2021   9.92
222            Padangsidimpuan  2021   7.53
243              Pakpak Bharat  2021   9.35
223           Pematang Siantar  2021   8.52
244                       RIAU  2021   7.12
245             SULAWESI BARAT  2021  11.29
246           SULAWESI SELATAN  2021   8.78
247            SULAWESI TENGAH  2021     13
248          SULAWESI TENGGARA  2021  11.66
249             SULAWESI UTARA  2021   7.77
250             SUMATERA BARAT  2021   6.63
251           SUMATERA SELATAN  2021  12.84
252             SUMATERA UTARA  2021   9.01
253                    Samosir  2021  12.68
254            Serdang Bedagai  2021    8.3
224                    Sibolga  2021  12.33
255                 Simalungun  2021   8.81
225              Tanjung Balai  2021   13.4
256           Tapanuli Selatan  2021    8.8
257            Tapanuli Tengah  2021  12.67
258             Tapanuli Utara  2021   9.72
226              Tebing Tinggi  2021   10.3
259                       Toba  2021   8.99
260                       ACEH  2022  14.64
261                     Asahan  2022   8.64
262                       BALI  2022   4.57
263                     BANTEN  2022   6.16
264                   BENGKULU  2022  14.62
265                  Batu Bara  2022  11.53
284                     Binjai  2022    5.1
266              DI YOGYAKARTA  2022  11.34
267                DKI JAKARTA  2022   4.69
268                      Dairi  2022   7.88
269               Deli Serdang  2022   3.62
270                  GORONTALO  2022  15.42
285               Gunungsitoli  2022  14.81
271         Humbang Hasundutan  2022   8.86
272                      JAMBI  2022   7.62
273                 JAWA BARAT  2022   8.06
274                JAWA TENGAH  2022  10.93
275                 JAWA TIMUR  2022  10.38
276           KALIMANTAN BARAT  2022   6.73
277         KALIMANTAN SELATAN  2022   4.49
278          KALIMANTAN TENGAH  2022   5.28
279           KALIMANTAN TIMUR  2022   6.31
280           KALIMANTAN UTARA  2022   6.77
281  KEPULAUAN BANGKA BELITUNG  2022   4.45
282             KEPULAUAN RIAU  2022   6.24
283                       Karo  2022   8.17
292                    LAMPUNG  2022  11.57
293               Labuhan Batu  2022   8.26
294       Labuhan Batu Selatan  2022   8.09
295         Labuhan Batu Utara  2022   9.09
296                    Langkat  2022   9.49
297                     MALUKU  2022  15.97
298               MALUKU UTARA  2022   6.23
299           Mandailing Natal  2022   8.92
286                      Medan  2022   8.07
300        NUSA TENGGARA BARAT  2022  13.68
301        NUSA TENGGARA TIMUR  2022  20.05
302                       Nias  2022     16
303                 Nias Barat  2022  24.75
304               Nias Selatan  2022  16.48
305                 Nias Utara  2022   23.4
306               Padang Lawas  2022   8.05
307         Padang Lawas Utara  2022   8.94
287            Padangsidimpuan  2022   6.89
308              Pakpak Bharat  2022   8.66
288           Pematang Siantar  2022   7.88
309                       RIAU  2022   6.78
310             SULAWESI BARAT  2022  11.75
311           SULAWESI SELATAN  2022   8.63
312            SULAWESI TENGAH  2022  12.33
313          SULAWESI TENGGARA  2022  11.17
314             SULAWESI UTARA  2022   7.28
315             SUMATERA BARAT  2022   5.92
316           SUMATERA SELATAN  2022   11.9
317             SUMATERA UTARA  2022   8.42
318                    Samosir  2022  11.77
319            Serdang Bedagai  2022   7.82
289                    Sibolga  2022  11.47
320                 Simalungun  2022   8.26
290              Tanjung Balai  2022  12.45
321           Tapanuli Selatan  2022   8.07
322            Tapanuli Tengah  2022  11.71
323             Tapanuli Utara  2022   8.93
291              Tebing Tinggi  2022   9.59
324                       Toba  2022   8.89
325                       ACEH  2023  14.45
326                     Asahan  2023   8.21
327                       BALI  2023   4.25
328                     BANTEN  2023   6.17
329                   BENGKULU  2023  14.04
330                  Batu Bara  2023  11.38
349                     Binjai  2023   4.79
331              DI YOGYAKARTA  2023  11.04
332                DKI JAKARTA  2023   4.44
333                      Dairi  2023   7.47
334               Deli Serdang  2023   3.44
335                  GORONTALO  2023  15.15
350               Gunungsitoli  2023  14.78
336         Humbang Hasundutan  2023   8.69
337                      JAMBI  2023   7.58
338                 JAWA BARAT  2023   7.62
339                JAWA TENGAH  2023  10.77
340                 JAWA TIMUR  2023  10.35
341           KALIMANTAN BARAT  2023   6.71
342         KALIMANTAN SELATAN  2023   4.29
343          KALIMANTAN TENGAH  2023   5.11
344           KALIMANTAN TIMUR  2023   6.11
345           KALIMANTAN UTARA  2023   6.45
346  KEPULAUAN BANGKA BELITUNG  2023   4.52
347             KEPULAUAN RIAU  2023   5.69
348                       Karo  2023   7.98
357                    LAMPUNG  2023  11.11
358               Labuhan Batu  2023   7.99
359       Labuhan Batu Selatan  2023   8.06
360         Labuhan Batu Utara  2023   9.08
361                    Langkat  2023   9.23
362                     MALUKU  2023  16.42
363               MALUKU UTARA  2023   6.46
364           Mandailing Natal  2023   8.86
351                      Medan  2023      8
365        NUSA TENGGARA BARAT  2023  13.85
366        NUSA TENGGARA TIMUR  2023  19.96
367                       Nias  2023   15.1
368                 Nias Barat  2023  22.81
369               Nias Selatan  2023  16.39
370                 Nias Utara  2023  21.79
371               Padang Lawas  2023   7.89
372         Padang Lawas Utara  2023   8.79
352            Padangsidimpuan  2023   6.85
373              Pakpak Bharat  2023   7.54
353           Pematang Siantar  2023   7.24
374                       RIAU  2023   6.68
375             SULAWESI BARAT  2023  11.49
376           SULAWESI SELATAN  2023    8.7
377            SULAWESI TENGAH  2023  12.41
378          SULAWESI TENGGARA  2023  11.43
379             SULAWESI UTARA  2023   7.38
380             SUMATERA BARAT  2023   5.95
381           SUMATERA SELATAN  2023  11.78
382             SUMATERA UTARA  2023   8.15
383                    Samosir  2023  11.66
384            Serdang Bedagai  2023   7.44
354                    Sibolga  2023  11.42
385                 Simalungun  2023   7.87
355              Tanjung Balai  2023  12.21
386           Tapanuli Selatan  2023   7.01
387            Tapanuli Tengah  2023   11.5
388             Tapanuli Utara  2023   8.54
356              Tebing Tinggi  2023   9.49
389                       Toba  2023   8.04
390                       ACEH  2024  14.23
391                     Asahan  2024   8.12
392                       BALI  2024      4
393                     BANTEN  2024   5.84
394                   BENGKULU  2024  13.56
395                  Batu Bara  2024  10.94
414                     Binjai  2024   4.75
396              DI YOGYAKARTA  2024  10.83
397                DKI JAKARTA  2024    4.3
398                      Dairi  2024    7.1
399               Deli Serdang  2024   3.44
400                  GORONTALO  2024  14.57
415               Gunungsitoli  2024  14.72
401         Humbang Hasundutan  2024   8.44
402                      JAMBI  2024    7.1
403                 JAWA BARAT  2024   7.46
404                JAWA TENGAH  2024  10.47
405                 JAWA TIMUR  2024   9.79
406           KALIMANTAN BARAT  2024   6.32
407         KALIMANTAN SELATAN  2024   4.11
408          KALIMANTAN TENGAH  2024   5.17
409           KALIMANTAN TIMUR  2024   5.78
410           KALIMANTAN UTARA  2024   6.32
411  KEPULAUAN BANGKA BELITUNG  2024   4.55
412             KEPULAUAN RIAU  2024   5.37
413                       Karo  2024   7.37
422                    LAMPUNG  2024  10.69
423               Labuhan Batu  2024   7.84
424       Labuhan Batu Selatan  2024   7.73
425         Labuhan Batu Utara  2024   8.98
426                    Langkat  2024   9.04
427                     MALUKU  2024  16.05
428               MALUKU UTARA  2024   6.32
429           Mandailing Natal  2024   8.69
416                      Medan  2024   7.94
430        NUSA TENGGARA BARAT  2024  12.91
431        NUSA TENGGARA TIMUR  2024  19.48
432                       Nias  2024  14.89
433                 Nias Barat  2024  22.68
434               Nias Selatan  2024  16.32
435                 Nias Utara  2024   21.5
436               Padang Lawas  2024   7.87
437         Padang Lawas Utara  2024   8.97
417            Padangsidimpuan  2024   6.23
438              Pakpak Bharat  2024   6.87
418           Pematang Siantar  2024    7.2
439                       RIAU  2024   6.67
440             SULAWESI BARAT  2024  11.21
441           SULAWESI SELATAN  2024   8.06
442            SULAWESI TENGAH  2024  11.77
443          SULAWESI TENGGARA  2024  11.21
444             SULAWESI UTARA  2024   7.25
445             SUMATERA BARAT  2024   5.97
446           SUMATERA SELATAN  2024  10.97
447             SUMATERA UTARA  2024   7.99
448                    Samosir  2024  11.63
449            Serdang Bedagai  2024   6.97
419                    Sibolga  2024  11.39
450                 Simalungun  2024   7.72
420              Tanjung Balai  2024  11.97
451           Tapanuli Selatan  2024   6.92
452            Tapanuli Tengah  2024   11.8
453             Tapanuli Utara  2024   8.21

In [35]:
# combine GR into dfP0
dfP0_melted = pd.merge(dfP0_melted, dfGR_melted, on=['Daerah', 'Tahun'], how='outer').sort_values(by=['Tahun', 'Daerah']).reset_index(drop=True)
print(dfP0_melted.to_string())

                        Daerah Tahun     P0      GR
0                         ACEH  2018  15.97  0.3215
1                       Asahan  2018  10.25  0.2912
2                         BALI  2018   4.01  0.3705
3                       BANTEN  2018   5.24   0.376
4                     BENGKULU  2018  15.43  0.3585
5                    Batu Bara  2018  12.57  0.2494
6                       Binjai  2018   5.88  0.3085
7                DI YOGYAKARTA  2018  12.13  0.4315
8                  DKI JAKARTA  2018   3.57   0.392
9                        Dairi  2018    8.2  0.2649
10                Deli Serdang  2018   4.13  0.2935
11                   GORONTALO  2018  16.81    0.41
12                Gunungsitoli  2018  18.44  0.3608
13          Humbang Hasundutan  2018      9  0.2909
14                       JAMBI  2018   7.92  0.3345
15                  JAWA BARAT  2018   7.45   0.406
16                 JAWA TENGAH  2018  11.32  0.3675
17                  JAWA TIMUR  2018  10.98   0.375
18            KALIMANTAN BARAT  2018   7.77   0.332
19          KALIMANTAN SELATAN  2018   4.54   0.342
20           KALIMANTAN TENGAH  2018   5.17   0.343
21            KALIMANTAN TIMUR  2018   6.03   0.342
22            KALIMANTAN UTARA  2018   7.09  0.3035
23   KEPULAUAN BANGKA BELITUNG  2018   5.25  0.2765
24              KEPULAUAN RIAU  2018    6.2  0.3345
25                        Karo  2018   8.67  0.2682
26                     LAMPUNG  2018  13.14   0.336
27                Labuhan Batu  2018   8.61  0.2936
28        Labuhan Batu Selatan  2018     10  0.2427
29          Labuhan Batu Utara  2018  10.12  0.2819
30                     Langkat  2018   10.2  0.2534
31                      MALUKU  2018  18.12  0.3345
32                MALUKU UTARA  2018   6.64   0.332
33            Mandailing Natal  2018   9.58  0.2574
34                       Medan  2018   8.25  0.3144
35         NUSA TENGGARA BARAT  2018  14.75  0.3815
36         NUSA TENGGARA TIMUR  2018  21.35   0.355
37                        Nias  2018  16.37  0.2645
38                  Nias Barat  2018  26.72  0.2833
39                Nias Selatan  2018  16.65  0.3295
40                  Nias Utara  2018  26.56  0.2374
41                Padang Lawas  2018   8.41  0.2985
42          Padang Lawas Utara  2018  10.06  0.2989
43             Padangsidimpuan  2018   7.69  0.3593
44               Pakpak Bharat  2018   9.74  0.2393
45            Pematang Siantar  2018    8.7   0.334
46                        RIAU  2018   7.39   0.337
47              SULAWESI BARAT  2018  11.25   0.368
48            SULAWESI SELATAN  2018   9.06  0.3925
49             SULAWESI TENGAH  2018  14.01  0.3315
50           SULAWESI TENGGARA  2018  11.63  0.4005
51              SULAWESI UTARA  2018    7.8   0.383
52              SUMATERA BARAT  2018   6.65   0.313
53            SUMATERA SELATAN  2018   12.8  0.3495
54              SUMATERA UTARA  2018   9.22  0.3145
55                     Samosir  2018  13.38  0.2846
56             Serdang Bedagai  2018   8.22  0.2828
57                     Sibolga  2018  12.38  0.3032
58                  Simalungun  2018   9.31  0.2897
59               Tanjung Balai  2018  14.64   0.332
60            Tapanuli Selatan  2018   9.16  0.2727
61             Tapanuli Tengah  2018  13.17  0.3174
62              Tapanuli Utara  2018   9.75  0.2819
63               Tebing Tinggi  2018  10.27  0.3396
64                        Toba  2018   8.67  0.3279
65                        ACEH  2019  15.32    0.32
66                      Asahan  2019   9.68  0.2793
67                        BALI  2019   3.79   0.368
68                      BANTEN  2019   5.09   0.363
69                    BENGKULU  2019  15.23  0.3345
70                   Batu Bara  2019  12.14  0.2773
71                      Binjai  2019   5.66  0.3511
72               DI YOGYAKARTA  2019   11.7  0.4255
73                 DKI JAKARTA  2019   3.47  0.3925
74                       Dairi  2019    7.7  0.2873
75                Deli Serdang  2019   3.89  0.2732
76                   GORONTALO  2019  15.52  0.4085
77                Gunungsitoli  2019  16.23  0.3183
78          Humbang Hasundutan  2019   8.75  0.2893
79                       JAMBI  2019    7.6  0.3225
80                  JAWA BARAT  2019   6.91     0.4
81                 JAWA TENGAH  2019   10.8  0.3595
82                  JAWA TIMUR  2019  10.37   0.367
83            KALIMANTAN BARAT  2019   7.49  0.3225
84          KALIMANTAN SELATAN  2019   4.55   0.334
85           KALIMANTAN TENGAH  2019   4.98  0.3355
86            KALIMANTAN TIMUR  2019   5.94  0.3325
87            KALIMANTAN UTARA  2019   6.63  0.2935
88   KEPULAUAN BANGKA BELITUNG  2019   4.62  0.2655
89              KEPULAUAN RIAU  2019    5.9   0.339
90                        Karo  2019   8.23  0.2642
91                     LAMPUNG  2019  12.62    0.33
92                Labuhan Batu  2019   8.44  0.2767
93        Labuhan Batu Selatan  2019   8.94  0.2497
94          Labuhan Batu Utara  2019   9.57  0.2668
95                     Langkat  2019   9.91   0.266
96                      MALUKU  2019  17.69   0.322
97                MALUKU UTARA  2019   6.77   0.311
98            Mandailing Natal  2019   9.11  0.2623
99                       Medan  2019   8.08  0.3519
100        NUSA TENGGARA BARAT  2019  14.56  0.3765
101        NUSA TENGGARA TIMUR  2019  21.09  0.3555
102                       Nias  2019  15.94   0.274
103                 Nias Barat  2019  25.51  0.2578
104               Nias Selatan  2019  16.45  0.3186
105                 Nias Utara  2019  24.99  0.2844
106               Padang Lawas  2019   8.28  0.2313
107         Padang Lawas Utara  2019    9.6  0.2702
108            Padangsidimpuan  2019   7.26  0.3098
109              Pakpak Bharat  2019   9.27  0.2791
110           Pematang Siantar  2019   8.63  0.3298
111                       RIAU  2019   7.08  0.3325
112             SULAWESI BARAT  2019  11.02   0.365
113           SULAWESI SELATAN  2019   8.69    0.39
114            SULAWESI TENGAH  2019  13.48  0.3285
115          SULAWESI TENGGARA  2019  11.24   0.396
116             SULAWESI UTARA  2019   7.66  0.3715
117             SUMATERA BARAT  2019   6.42  0.3065
118           SUMATERA SELATAN  2019  12.71   0.335
119             SUMATERA UTARA  2019   8.83   0.316
120                    Samosir  2019  12.52   0.301
121            Serdang Bedagai  2019    7.9  0.2571
122                    Sibolga  2019  12.36  0.2718
123                 Simalungun  2019   8.81  0.2738
124              Tanjung Balai  2019  14.04  0.2678
125           Tapanuli Selatan  2019    8.6  0.2467
126            Tapanuli Tengah  2019  12.53   0.309
127             Tapanuli Utara  2019   9.48  0.3065
128              Tebing Tinggi  2019   9.94  0.3237
129                       Toba  2019    8.6  0.2753
130                       ACEH  2020  14.99   0.321
131                     Asahan  2020   9.04  0.2605
132                       BALI  2020   3.78   0.369
133                     BANTEN  2020   5.92   0.364
134                   BENGKULU  2020  15.03  0.3285
135                  Batu Bara  2020  11.88  0.2592
136                     Binjai  2020   5.71  0.3244
137              DI YOGYAKARTA  2020  12.28  0.4355
138                DKI JAKARTA  2020   4.53  0.3995
139                      Dairi  2020   8.04  0.2706
140               Deli Serdang  2020   3.88   0.312
141                  GORONTALO  2020  15.22   0.407
142               Gunungsitoli  2020  16.41  0.3223
143         Humbang Hasundutan  2020   9.36  0.2464
144                      JAMBI  2020   7.58   0.318
145                 JAWA BARAT  2020   7.88  0.4005
146                JAWA TENGAH  2020  11.41  0.3605
147                 JAWA TIMUR  2020  11.09   0.365
148           KALIMANTAN BARAT  2020   7.17   0.321
149         KALIMANTAN SELATAN  2020   4.38  0.3415
150          KALIMANTAN TENGAH  2020   4.82  0.3245
151           KALIMANTAN TIMUR  2020    6.1  0.3315
152           KALIMANTAN UTARA  2020    6.8   0.296
153  KEPULAUAN BANGKA BELITUNG  2020   4.53  0.2595
154             KEPULAUAN RIAU  2020   5.92  0.3365
155                       Karo  2020    8.7  0.2706
156                    LAMPUNG  2020  12.34  0.3235
157               Labuhan Batu  2020   8.44  0.2715
158       Labuhan Batu Selatan  2020   8.34  0.1935
159         Labuhan Batu Utara  2020   9.53  0.2624
160                    Langkat  2020   9.73  0.2378
161                     MALUKU  2020  17.44   0.322
162               MALUKU UTARA  2020   6.78   0.299
163           Mandailing Natal  2020   9.18  0.2478
164                      Medan  2020   8.01  0.3199
165        NUSA TENGGARA BARAT  2020  13.97   0.381
166        NUSA TENGGARA TIMUR  2020   20.9   0.355
167                       Nias  2020   16.6  0.2512
168                 Nias Barat  2020  25.69  0.2339
169               Nias Selatan  2020  16.74  0.2865
170                 Nias Utara  2020  25.07  0.2506
171               Padang Lawas  2020   8.37  0.2653
172         Padang Lawas Utara  2020    9.7  0.2283
173            Padangsidimpuan  2020    7.4  0.3538
174              Pakpak Bharat  2020   9.28  0.2475
175           Pematang Siantar  2020   8.27  0.3362
176                       RIAU  2020   6.82   0.325
177             SULAWESI BARAT  2020  10.87    0.36
178           SULAWESI SELATAN  2020   8.72  0.3855
179            SULAWESI TENGAH  2020  12.92  0.3235
180          SULAWESI TENGGARA  2020     11  0.3885
181             SULAWESI UTARA  2020   7.62   0.369
182             SUMATERA BARAT  2020   6.28   0.303
183           SUMATERA SELATAN  2020  12.66  0.3385
184             SUMATERA UTARA  2020   8.75   0.315
185                    Samosir  2020  12.48  0.3175
186            Serdang Bedagai  2020   7.97   0.262
187                    Sibolga  2020  11.95  0.2912
188                 Simalungun  2020   8.46   0.295
189              Tanjung Balai  2020  13.33  0.2716
190           Tapanuli Selatan  2020   8.47  0.2022
191            Tapanuli Tengah  2020  12.38   0.335
192             Tapanuli Utara  2020   9.37  0.2867
193              Tebing Tinggi  2020   9.85  0.3337
194                       Toba  2020   8.71  0.2903
195                       ACEH  2021  15.33  0.3235
196                     Asahan  2021   9.35  0.2441
197                       BALI  2021   4.53  0.3765
198                     BANTEN  2021   6.66   0.364
199                   BENGKULU  2021  15.22  0.3235
200                  Batu Bara  2021  12.38  0.2396
201                     Binjai  2021   5.81  0.2903
202              DI YOGYAKARTA  2021   12.8  0.4385
203                DKI JAKARTA  2021   4.72    0.41
204                      Dairi  2021   8.31  0.2268
205               Deli Serdang  2021   4.01  0.2628
206                  GORONTALO  2021  15.61  0.4085
207               Gunungsitoli  2021  16.45  0.3166
208         Humbang Hasundutan  2021   9.65  0.3043
209                      JAMBI  2021   8.09   0.318
210                 JAWA BARAT  2021    8.4   0.409
211                JAWA TENGAH  2021  11.79    0.37
212                 JAWA TIMUR  2021   11.4   0.369
213           KALIMANTAN BARAT  2021   7.15   0.314
214         KALIMANTAN SELATAN  2021   4.83  0.3275
215          KALIMANTAN TENGAH  2021   5.16  0.3215
216           KALIMANTAN TIMUR  2021   6.54  0.3325
217           KALIMANTAN UTARA  2021   7.36  0.2885
218  KEPULAUAN BANGKA BELITUNG  2021    4.9  0.2515
219             KEPULAUAN RIAU  2021   6.12   0.341
220                       Karo  2021   8.79  0.2327
221                    LAMPUNG  2021  12.62  0.3185
222               Labuhan Batu  2021   8.74  0.2564
223       Labuhan Batu Selatan  2021   8.53  0.2317
224         Labuhan Batu Utara  2021  10.02  0.2431
225                    Langkat  2021  10.12  0.2381
226                     MALUKU  2021  17.87   0.315
227               MALUKU UTARA  2021   6.89   0.289
228           Mandailing Natal  2021   9.49  0.2403
229                      Medan  2021   8.34   0.402
230        NUSA TENGGARA BARAT  2021  14.14  0.3825
231        NUSA TENGGARA TIMUR  2021  20.99  0.3425
232                       Nias  2021  16.82  0.2452
233                 Nias Barat  2021  26.42  0.2238
234               Nias Selatan  2021  16.92  0.2411
235                 Nias Utara  2021  25.66  0.2359
236               Padang Lawas  2021   8.69  0.2525
237         Padang Lawas Utara  2021   9.92  0.2547
238            Padangsidimpuan  2021   7.53  0.3101
239              Pakpak Bharat  2021   9.35  0.2421
240           Pematang Siantar  2021   8.52  0.3076
241                       RIAU  2021   7.12  0.3265
242             SULAWESI BARAT  2021  11.29   0.361
243           SULAWESI SELATAN  2021   8.78  0.3795
244            SULAWESI TENGAH  2021     13   0.321
245          SULAWESI TENGGARA  2021  11.66   0.392
246             SULAWESI UTARA  2021   7.77   0.362
247             SUMATERA BARAT  2021   6.63   0.303
248           SUMATERA SELATAN  2021  12.84  0.3405
249             SUMATERA UTARA  2021   9.01  0.3135
250                    Samosir  2021  12.68  0.2735
251            Serdang Bedagai  2021    8.3  0.2287
252                    Sibolga  2021  12.33  0.2764
253                 Simalungun  2021   8.81  0.2641
254              Tanjung Balai  2021   13.4  0.2477
255           Tapanuli Selatan  2021    8.8  0.2564
256            Tapanuli Tengah  2021  12.67  0.2917
257             Tapanuli Utara  2021   9.72  0.2766
258              Tebing Tinggi  2021   10.3   0.344
259                       Toba  2021   8.99  0.2719
260                       ACEH  2022  14.64   0.301
261                     Asahan  2022   8.64   0.255
262                       BALI  2022   4.57  0.3625
263                     BANTEN  2022   6.16    0.37
264                   BENGKULU  2022  14.62   0.315
265                  Batu Bara  2022  11.53   0.243
266                     Binjai  2022    5.1   0.302
267              DI YOGYAKARTA  2022  11.34   0.449
268                DKI JAKARTA  2022   4.69  0.4175
269                      Dairi  2022   7.88   0.221
270               Deli Serdang  2022   3.62    0.27
271                  GORONTALO  2022  15.42  0.4205
272               Gunungsitoli  2022  14.81   0.303
273         Humbang Hasundutan  2022   8.86   0.258
274                      JAMBI  2022   7.62  0.3275
275                 JAWA BARAT  2022   8.06  0.4145
276                JAWA TENGAH  2022  10.93    0.37
277                 JAWA TIMUR  2022  10.38   0.368
278           KALIMANTAN BARAT  2022   6.73  0.3125
279         KALIMANTAN SELATAN  2022   4.49   0.313
280          KALIMANTAN TENGAH  2022   5.28   0.314
281           KALIMANTAN TIMUR  2022   6.31   0.322
282           KALIMANTAN UTARA  2022   6.77   0.271
283  KEPULAUAN BANGKA BELITUNG  2022   4.45  0.2455
284             KEPULAUAN RIAU  2022   6.24  0.3335
285                       Karo  2022   8.17   0.236
286                    LAMPUNG  2022  11.57  0.3135
287               Labuhan Batu  2022   8.26   0.278
288       Labuhan Batu Selatan  2022   8.09   0.247
289         Labuhan Batu Utara  2022   9.09   0.276
290                    Langkat  2022   9.49    0.26
291                     MALUKU  2022  15.97  0.3035
292               MALUKU UTARA  2022   6.23   0.294
293           Mandailing Natal  2022   8.92   0.244
294                      Medan  2022   8.07   0.399
295        NUSA TENGGARA BARAT  2022  13.68  0.3735
296        NUSA TENGGARA TIMUR  2022  20.05   0.337
297                       Nias  2022     16   0.275
298                 Nias Barat  2022  24.75    0.21
299               Nias Selatan  2022  16.48   0.223
300                 Nias Utara  2022   23.4   0.239
301               Padang Lawas  2022   8.05   0.227
302         Padang Lawas Utara  2022   8.94   0.245
303            Padangsidimpuan  2022   6.89   0.275
304              Pakpak Bharat  2022   8.66   0.274
305           Pematang Siantar  2022   7.88   0.321
306                       RIAU  2022   6.78  0.3245
307             SULAWESI BARAT  2022  11.75  0.3665
308           SULAWESI SELATAN  2022   8.63   0.371
309            SULAWESI TENGAH  2022  12.33  0.3065
310          SULAWESI TENGGARA  2022  11.17  0.3765
311             SULAWESI UTARA  2022   7.28   0.362
312             SUMATERA BARAT  2022   5.92   0.296
313           SUMATERA SELATAN  2022   11.9  0.3345
314             SUMATERA UTARA  2022   8.42   0.319
315                    Samosir  2022  11.77   0.298
316            Serdang Bedagai  2022   7.82    0.24
317                    Sibolga  2022  11.47   0.346
318                 Simalungun  2022   8.26   0.262
319              Tanjung Balai  2022  12.45   0.245
320           Tapanuli Selatan  2022   8.07   0.209
321            Tapanuli Tengah  2022  11.71   0.233
322             Tapanuli Utara  2022   8.93   0.242
323              Tebing Tinggi  2022   9.59   0.334
324                       Toba  2022   8.89   0.305
325                       ACEH  2023  14.45   0.296
326                     Asahan  2023   8.21    0.26
327                       BALI  2023   4.25   0.362
328                     BANTEN  2023   6.17   0.368
329                   BENGKULU  2023  14.04   0.333
330                  Batu Bara  2023  11.38   0.255
331                     Binjai  2023   4.79   0.318
332              DI YOGYAKARTA  2023  11.04   0.449
333                DKI JAKARTA  2023   4.44   0.431
334                      Dairi  2023   7.47   0.241
335               Deli Serdang  2023   3.44   0.295
336                  GORONTALO  2023  15.15   0.417
337               Gunungsitoli  2023  14.78   0.308
338         Humbang Hasundutan  2023   8.69   0.256
339                      JAMBI  2023   7.58   0.343
340                 JAWA BARAT  2023   7.62   0.425
341                JAWA TENGAH  2023  10.77   0.369
342                 JAWA TIMUR  2023  10.35   0.387
343           KALIMANTAN BARAT  2023   6.71   0.321
344         KALIMANTAN SELATAN  2023   4.29   0.313
345          KALIMANTAN TENGAH  2023   5.11   0.317
346           KALIMANTAN TIMUR  2023   6.11   0.322
347           KALIMANTAN UTARA  2023   6.45   0.277
348  KEPULAUAN BANGKA BELITUNG  2023   4.52   0.245
349             KEPULAUAN RIAU  2023   5.69    0.34
350                       Karo  2023   7.98    0.24
351                    LAMPUNG  2023  11.11   0.324
352               Labuhan Batu  2023   7.99   0.244
353       Labuhan Batu Selatan  2023   8.06   0.231
354         Labuhan Batu Utara  2023   9.08   0.238
355                    Langkat  2023   9.23   0.257
356                     MALUKU  2023  16.42   0.288
357               MALUKU UTARA  2023   6.46     0.3
358           Mandailing Natal  2023   8.86   0.249
359                      Medan  2023      8   0.373
360        NUSA TENGGARA BARAT  2023  13.85   0.375
361        NUSA TENGGARA TIMUR  2023  19.96   0.325
362                       Nias  2023   15.1   0.279
363                 Nias Barat  2023  22.81   0.208
364               Nias Selatan  2023  16.39   0.261
365                 Nias Utara  2023  21.79   0.228
366               Padang Lawas  2023   7.89   0.225
367         Padang Lawas Utara  2023   8.79   0.241
368            Padangsidimpuan  2023   6.85   0.267
369              Pakpak Bharat  2023   7.54   0.251
370           Pematang Siantar  2023   7.24   0.329
371                       RIAU  2023   6.68   0.324
372             SULAWESI BARAT  2023  11.49   0.351
373           SULAWESI SELATAN  2023    8.7   0.377
374            SULAWESI TENGAH  2023  12.41   0.304
375          SULAWESI TENGGARA  2023  11.43   0.371
376             SULAWESI UTARA  2023   7.38    0.37
377             SUMATERA BARAT  2023   5.95    0.28
378           SUMATERA SELATAN  2023  11.78   0.338
379             SUMATERA UTARA  2023   8.15   0.309
380                    Samosir  2023  11.66   0.251
381            Serdang Bedagai  2023   7.44   0.225
382                    Sibolga  2023  11.42   0.246

In [ ]:
# Convert P0 and GR columns to numeric if they aren't already
dfP0_melted['P0'] = pd.to_numeric(dfP0_melted['P0'], errors='coerce')
dfP0_melted['GR'] = pd.to_numeric(dfP0_melted['GR'], errors='coerce')

# Drop rows with NaN values after conversion
dfP0_melted = dfP0_melted.dropna(subset=['P0', 'GR']).reset_index(drop=True)

print(f"Number of rows after cleaning: {len(dfP0_melted)}")
print(dfP0_melted.dtypes)

# Regression Analysis

Let's perform several types of regression analysis to explore the relationship between poverty rate (P0) and Gini ratio (GR).

In [ ]:
# Import necessary libraries for regression analysis
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from scipy import stats

## Exploratory Data Analysis

First, let's visualize the relationship between P0 and GR.

In [ ]:
# Set up the plot style
plt.figure(figsize=(10, 6))
sns.set_style('whitegrid')

# Create a scatter plot with color based on year
scatter = sns.scatterplot(data=dfP0_melted, x='P0', y='GR', hue='Tahun', palette='viridis', alpha=0.7)

# Add labels and title
plt.title('Relationship Between Poverty Rate (P0) and Gini Ratio (GR)', fontsize=14)
plt.xlabel('Poverty Rate (P0)', fontsize=12)
plt.ylabel('Gini Ratio (GR)', fontsize=12)

# Add a legend
plt.legend(title='Year', bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.show()

In [ ]:
# Calculate correlation coefficient and p-value
corr, p_value = stats.pearsonr(dfP0_melted['P0'], dfP0_melted['GR'])
print(f"Pearson correlation coefficient: {corr:.4f}")
print(f"P-value: {p_value:.4f}")

# Display correlation heatmap
plt.figure(figsize=(8, 6))
correlation_matrix = dfP0_melted[['P0', 'GR']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('Correlation Heatmap between P0 and GR')
plt.tight_layout()
plt.show()

## Simple Linear Regression

Let's start with a simple linear regression model.

In [ ]:
# Prepare data for regression
X = dfP0_melted['P0'].values.reshape(-1, 1)  # Independent variable
y = dfP0_melted['GR'].values  # Dependent variable

# Split data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the linear regression model
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

# Make predictions
y_pred_train = linear_model.predict(X_train)
y_pred_test = linear_model.predict(X_test)

# Calculate performance metrics
train_r2 = r2_score(y_train, y_pred_train)
test_r2 = r2_score(y_test, y_pred_test)
train_mse = mean_squared_error(y_train, y_pred_train)
test_mse = mean_squared_error(y_test, y_pred_test)

print(f"Linear Regression Coefficients: {linear_model.coef_}")
print(f"Linear Regression Intercept: {linear_model.intercept_}")
print(f"R² (training): {train_r2:.4f}")
print(f"R² (testing): {test_r2:.4f}")
print(f"MSE (training): {train_mse:.6f}")
print(f"MSE (testing): {test_mse:.6f}")

In [ ]:
# Visualize linear regression results
plt.figure(figsize=(10, 6))

# Plot the original data points
plt.scatter(X_train, y_train, color='blue', alpha=0.5, label='Training Data')
plt.scatter(X_test, y_test, color='green', alpha=0.5, label='Testing Data')

# Sort X values for clean line plot
X_line = np.linspace(min(X.flatten()), max(X.flatten()), 100).reshape(-1, 1)
y_line = linear_model.predict(X_line)

# Plot the regression line
plt.plot(X_line, y_line, color='red', linewidth=2, label='Linear Regression')

# Add labels and title
plt.title('Linear Regression: Poverty Rate (P0) vs Gini Ratio (GR)', fontsize=14)
plt.xlabel('Poverty Rate (P0)', fontsize=12)
plt.ylabel('Gini Ratio (GR)', fontsize=12)
plt.legend()

# Add the equation to the plot
equation = f"GR = {linear_model.intercept_:.4f} + {linear_model.coef_[0]:.4f} × P0"
plt.text(0.05, 0.95, equation, transform=plt.gca().transAxes, fontsize=12)
plt.text(0.05, 0.90, f"R² = {test_r2:.4f}", transform=plt.gca().transAxes, fontsize=12)

plt.tight_layout()
plt.grid(True, alpha=0.3)
plt.show()

## Statistical Analysis with StatsModels

Let's use the statsmodels library for more detailed statistical analysis.

In [ ]:
# Add a constant to the independent variable (intercept term)
X_sm = sm.add_constant(X)

# Fit the OLS model
ols_model = sm.OLS(y, X_sm).fit()

# Print summary statistics
print(ols_model.summary())

## Polynomial Regression

Let's try polynomial regression to see if a non-linear model better fits the data.

In [ ]:
# Try polynomial features of degree 2
poly_features = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly_features.fit_transform(X)

# Split the polynomial features into training and testing sets
X_poly_train, X_poly_test, y_poly_train, y_poly_test = train_test_split(X_poly, y, test_size=0.2, random_state=42)

# Create and train the polynomial regression model
poly_model = LinearRegression()
poly_model.fit(X_poly_train, y_poly_train)

# Make predictions
y_poly_pred_train = poly_model.predict(X_poly_train)
y_poly_pred_test = poly_model.predict(X_poly_test)

# Calculate performance metrics
poly_train_r2 = r2_score(y_poly_train, y_poly_pred_train)
poly_test_r2 = r2_score(y_poly_test, y_poly_pred_test)
poly_train_mse = mean_squared_error(y_poly_train, y_poly_pred_train)
poly_test_mse = mean_squared_error(y_poly_test, y_poly_pred_test)

print(f"Polynomial Regression Coefficients: {poly_model.coef_}")
print(f"Polynomial Regression Intercept: {poly_model.intercept_}")
print(f"R² (training): {poly_train_r2:.4f}")
print(f"R² (testing): {poly_test_r2:.4f}")
print(f"MSE (training): {poly_train_mse:.6f}")
print(f"MSE (testing): {poly_test_mse:.6f}")

In [ ]:
# Visualize polynomial regression results
plt.figure(figsize=(10, 6))

# Plot the original data points
plt.scatter(X_train, y_train, color='blue', alpha=0.5, label='Training Data')
plt.scatter(X_test, y_test, color='green', alpha=0.5, label='Testing Data')

# Sort X values for clean curve plot
X_curve = np.linspace(min(X.flatten()), max(X.flatten()), 100).reshape(-1, 1)
X_curve_poly = poly_features.transform(X_curve)
y_curve = poly_model.predict(X_curve_poly)

# Plot the regression curve
plt.plot(X_curve, y_curve, color='red', linewidth=2, label='Polynomial Regression')

# Add labels and title
plt.title('Polynomial Regression: Poverty Rate (P0) vs Gini Ratio (GR)', fontsize=14)
plt.xlabel('Poverty Rate (P0)', fontsize=12)
plt.ylabel('Gini Ratio (GR)', fontsize=12)
plt.legend()

# Add the equation and R² to the plot
equation = f"GR = {poly_model.intercept_:.4f} + {poly_model.coef_[0]:.4f}×P0 + {poly_model.coef_[1]:.6f}×P0²"
plt.text(0.05, 0.95, equation, transform=plt.gca().transAxes, fontsize=12)
plt.text(0.05, 0.90, f"R² = {poly_test_r2:.4f}", transform=plt.gca().transAxes, fontsize=12)

plt.tight_layout()
plt.grid(True, alpha=0.3)
plt.show()

## Analysis by Year

Let's analyze how the relationship between P0 and GR changes over the years.

In [ ]:
# Convert Tahun to numeric for consistent analysis
dfP0_melted['Tahun'] = pd.to_numeric(dfP0_melted['Tahun'])

# Set up a figure with subplots for each year
years = sorted(dfP0_melted['Tahun'].unique())
num_years = len(years)
fig, axes = plt.subplots(nrows=(num_years+1)//2, ncols=2, figsize=(15, 12))
axes = axes.flatten()  # Flatten the 2D array of axes for easy iteration

# For each year, fit a linear regression and plot
yearly_models = {}

for i, year in enumerate(years):
    # Filter data for the current year
    year_data = dfP0_melted[dfP0_melted['Tahun'] == year]
    X_year = year_data['P0'].values.reshape(-1, 1)
    y_year = year_data['GR'].values
    
    # Fit linear regression for this year
    if len(X_year) > 1:  # Ensure there's enough data to fit
        model = LinearRegression().fit(X_year, y_year)
        yearly_models[year] = model
        
        # Calculate R²
        y_pred = model.predict(X_year)
        r2 = r2_score(y_year, y_pred)
        
        # Plot on the corresponding subplot
        axes[i].scatter(X_year, y_year, alpha=0.7)
        
        # Plot the regression line
        X_line = np.linspace(min(X_year.flatten()), max(X_year.flatten()), 100).reshape(-1, 1)
        y_line = model.predict(X_line)
        axes[i].plot(X_line, y_line, color='red', linewidth=2)
        
        # Add title with year and R²
        axes[i].set_title(f'Year {int(year)}: R² = {r2:.4f}')
        axes[i].set_xlabel('Poverty Rate (P0)')
        axes[i].set_ylabel('Gini Ratio (GR)')
        
        # Add the equation to the plot
        equation = f"GR = {model.intercept_:.4f} + {model.coef_[0]:.4f}×P0"
        axes[i].text(0.05, 0.95, equation, transform=axes[i].transAxes, fontsize=10)
    else:
        axes[i].text(0.5, 0.5, f'Insufficient data for {int(year)}', ha='center')

# Remove any unused subplots
for j in range(i+1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

## Year-over-Year Trend Analysis

Let's analyze how the regression coefficients change over time.

In [ ]:
# Extract coefficients and intercepts from yearly models
years_list = []
slopes = []
intercepts = []
r2_values = []

for year, model in yearly_models.items():
    # Filter data for the current year to calculate R²
    year_data = dfP0_melted[dfP0_melted['Tahun'] == year]
    X_year = year_data['P0'].values.reshape(-1, 1)
    y_year = year_data['GR'].values
    y_pred = model.predict(X_year)
    r2 = r2_score(y_year, y_pred)
    
    years_list.append(year)
    slopes.append(model.coef_[0])
    intercepts.append(model.intercept_)
    r2_values.append(r2)

# Create a DataFrame to store the trend data
trend_df = pd.DataFrame({
    'Year': years_list,
    'Slope': slopes,
    'Intercept': intercepts,
    'R²': r2_values
})

trend_df.sort_values('Year', inplace=True)
print(trend_df)

In [ ]:
# Visualize the trend of coefficients over the years
fig, axes = plt.subplots(nrows=3, figsize=(12, 10), sharex=True)

# Plot slope trend
axes[0].plot(trend_df['Year'], trend_df['Slope'], marker='o', linestyle='-', color='blue')
axes[0].set_ylabel('Slope Coefficient')
axes[0].set_title('Trend of Slope Coefficient Over Years')
axes[0].grid(alpha=0.3)

# Plot intercept trend
axes[1].plot(trend_df['Year'], trend_df['Intercept'], marker='o', linestyle='-', color='green')
axes[1].set_ylabel('Intercept')
axes[1].set_title('Trend of Intercept Over Years')
axes[1].grid(alpha=0.3)

# Plot R² trend
axes[2].plot(trend_df['Year'], trend_df['R²'], marker='o', linestyle='-', color='red')
axes[2].set_ylabel('R² Value')
axes[2].set_title('Trend of R² Over Years')
axes[2].set_xlabel('Year')
axes[2].grid(alpha=0.3)

# Set x-ticks to only show integer years
axes[2].set_xticks(sorted(trend_df['Year']))
axes[2].set_xticklabels([str(int(year)) for year in sorted(trend_df['Year'])])

plt.tight_layout()
plt.show()

## Multi-variable Analysis

Let's create a model that considers both P0 and Year as predictors.

In [ ]:
# Prepare data for multivariable regression
X_multi = dfP0_melted[['P0', 'Tahun']].values
y_multi = dfP0_melted['GR'].values

# Split data into training and testing sets
X_multi_train, X_multi_test, y_multi_train, y_multi_test = train_test_split(
    X_multi, y_multi, test_size=0.2, random_state=42
)

# Create and train multivariable linear regression model
multi_model = LinearRegression()
multi_model.fit(X_multi_train, y_multi_train)

# Make predictions
y_multi_pred_train = multi_model.predict(X_multi_train)
y_multi_pred_test = multi_model.predict(X_multi_test)

# Calculate performance metrics
multi_train_r2 = r2_score(y_multi_train, y_multi_pred_train)
multi_test_r2 = r2_score(y_multi_test, y_multi_pred_test)
multi_train_mse = mean_squared_error(y_multi_train, y_multi_pred_train)
multi_test_mse = mean_squared_error(y_multi_test, y_multi_pred_test)

print(f"Multivariable Regression Coefficients: [P0, Year] = {multi_model.coef_}")
print(f"Multivariable Regression Intercept: {multi_model.intercept_}")
print(f"R² (training): {multi_train_r2:.4f}")
print(f"R² (testing): {multi_test_r2:.4f}")
print(f"MSE (training): {multi_train_mse:.6f}")
print(f"MSE (testing): {multi_test_mse:.6f}")

In [ ]:
# Add a constant to the independent variables for statsmodels
X_multi_sm = sm.add_constant(dfP0_melted[['P0', 'Tahun']])

# Fit the OLS model
multi_ols_model = sm.OLS(dfP0_melted['GR'], X_multi_sm).fit()

# Print summary statistics
print(multi_ols_model.summary())

## Comparison of Models

Let's compare all the different regression models we've built.

In [ ]:
# Create a DataFrame to compare different models
models_comparison = pd.DataFrame({
    'Model': ['Linear Regression', 'Polynomial Regression', 'Multivariable Regression'],
    'Training R²': [train_r2, poly_train_r2, multi_train_r2],
    'Testing R²': [test_r2, poly_test_r2, multi_test_r2],
    'Training MSE': [train_mse, poly_train_mse, multi_train_mse],
    'Testing MSE': [test_mse, poly_test_mse, multi_test_mse]
})

print(models_comparison)

In [ ]:
# Visualize the comparison of models (R² values)
plt.figure(figsize=(10, 6))

# Create grouped bar plot
bar_width = 0.35
indices = np.arange(len(models_comparison))

plt.bar(indices - bar_width/2, models_comparison['Training R²'], bar_width, label='Training R²', color='skyblue')
plt.bar(indices + bar_width/2, models_comparison['Testing R²'], bar_width, label='Testing R²', color='lightgreen')

plt.xlabel('Model Type')
plt.ylabel('R² Value')
plt.title('Comparison of Models: R² Values')
plt.xticks(indices, models_comparison['Model'], rotation=45)
plt.legend()
plt.grid(axis='y', alpha=0.3)

# Add value labels on the bars
for i, v in enumerate(models_comparison['Training R²']):
    plt.text(i - bar_width/2, v + 0.01, f'{v:.4f}', ha='center', va='bottom', fontsize=9, rotation=90)
    
for i, v in enumerate(models_comparison['Testing R²']):
    plt.text(i + bar_width/2, v + 0.01, f'{v:.4f}', ha='center', va='bottom', fontsize=9, rotation=90)

plt.tight_layout()
plt.show()

## Conclusion

Based on our comprehensive regression analysis, we can draw several insights about the relationship between poverty rate (P0) and Gini Ratio (GR):

In [ ]:
# Save the best model for future use
import joblib

# Determine which model performed the best based on testing R²
best_model_idx = models_comparison['Testing R²'].idxmax()
best_model_name = models_comparison.loc[best_model_idx, 'Model']

print(f"The best performing model is: {best_model_name}")

# Save the corresponding model
if best_model_name == 'Linear Regression':
    joblib.dump(linear_model, 'best_regression_model.joblib')
    best_model = linear_model
elif best_model_name == 'Polynomial Regression':
    joblib.dump(poly_model, 'best_regression_model.joblib')
    # Also save the polynomial features transformer
    joblib.dump(poly_features, 'poly_features_transformer.joblib')
    best_model = poly_model
elif best_model_name == 'Multivariable Regression':
    joblib.dump(multi_model, 'best_regression_model.joblib')
    best_model = multi_model

print("Model saved successfully.")