In [1]:
import pandas as pd 
import numpy as np
import os

In [2]:
def loadGRKota():
    folder_path = 'data'
    dfs = []
    for filename in os.listdir(folder_path):
        if filename.startswith('GR Kota'):
            file_path = os.path.join(folder_path, filename)
            df = pd.read_csv(file_path)
            dfs.append(df)
    return dfs

In [3]:
dfGRKota = loadGRKota()

In [ ]:
def cleandf(df):
    # Set second row as the header
    df.columns = df.iloc[1]
    
    # #remove 1st and 2nd row
    df = df.iloc[2:]

    # Rename first column to 'Wilayah'
    df = df.rename(columns={df.columns[0]: 'Wilayah'})
        
    return df

In [5]:
dfGRKota = [cleandf(df) for df in dfGRKota]

In [6]:
merged_df = dfGRKota[0]
for df in dfGRKota[1:]:
    merged_df = pd.merge(merged_df, df, on='Wilayah', how='outer')

In [7]:
merged_df

,Wilayah,GINI RATIO SUMATERA UTARA MENURUT KABUPATEN/KOTA_x,NaN,NaN,GINI RATIO SUMATERA UTARA MENURUT KABUPATEN/KOTA_y,NaN,NaN,GINI RATIO SUMATERA UTARA MENURUT KABUPATEN/KOTA,NaN,NaN
0,Asahan,0.2826,0.2668,0.2912,0.2793,0.2605,0.2441,0.255,0.260,0.248
1,Batu Bara,0.2676,0.2335,0.2494,0.2773,0.2592,0.2396,0.243,0.255,0.258
2,Binjai,0.3155,0.3163,0.3085,0.3511,0.3244,0.2903,0.302,0.318,0.312
3,Dairi,0.3006,0.2403,0.2649,0.2873,0.2706,0.2268,0.221,0.241,0.215
4,Deli Serdang,0.2823,0.2814,0.2935,0.2732,0.3120,0.2628,0.27,0.295,0.262
5,Gunungsitoli,0.3569,0.3463,0.3608,0.3183,0.3223,0.3166,0.303,0.308,0.277
6,Humbang Hasundutan,0.275,0.2982,0.2909,0.2893,0.2464,0.3043,0.258,0.256,0.302
7,Karo,0.3283,0.2678,0.2682,0.2642,0.2706,0.2327,0.236,0.240,0.214
8,Labuanbatu Utara,0.2549,0.2665,0.2819,0.2668,0.2624,0.2431,0.276,0.238,0.239
9,Labuhan Batu,0.3082,0.2792,0.2936,0.2767,0.2715,0.2564,0.278,0.244,0.251
10,Labuhanbatu Selatan,0.2435,0.2197,0.2427,0.2497,0.1935,0.2317,0.247,0.231,0.212
11,Langkat,0.2834,0.2489,0.2534,0.266,0.2378,0.2381,0.26,0.257,0.260
12,Mandailing Natal,0.27,0.2523,0.2574,0.2623,0.2478,0.2403,0.244,0.249,0.250
13,Medan,0.3328,0.3520,0.3144,0.3519,0.3199,0.4020,0.399,0.373,0.356
14,Nias,0.2735,0.2491,0.2645,0.274,0.2512,0.2452,0.275,0.279,0.247
15,Nias Barat,0.2899,0.2469,0.2833,0.2578,0.2339,0.2238,0.21,0.208,0.219
16,Nias Selatan,0.2136,0.2694,0.3295,0.3186,0.2865,0.2411,0.223,0.261,0.247
17,Nias Utara,0.266,0.2685,0.2374,0.2844,0.2506,0.2359,0.239,0.228,0.234
18,Padang Lawas,0.3256,0.2482,0.2985,0.2313,0.2653,0.2525,0.227,0.225,0.224
19,Padang Lawas Utara,0.2525,0.2498,0.2989,0.2702,0.2283,0.2547,0.245,0.241,0.223
20,Padangsidimpuan,0.3335,0.3236,0.3593,0.3098,0.3538,0.3101,0.275,0.267,0.296
21,Pakpak Bharat,0.2644,0.2555,0.2393,0.2791,0.2475,0.2421,0.274,0.251,0.262
22,Pematangsiantar,0.3213,0.3494,0.3340,0.3298,0.3362,0.3076,0.321,0.329,0.297
23,Samosir,0.2764,0.2870,0.2846,0.301,0.3175,0.2735,0.298,0.251,0.238
24,Serdang Bedagai,0.2545,0.2754,0.2828,0.2571,0.2620,0.2287,0.24,0.225,0.242
25,Sibolga,0.3442,0.3234,0.3032,0.2718,0.2912,0.2764,0.346,0.246,0.313
26,Simalungun,0.296,0.2554,0.2897,0.2738,0.2950,0.2641,0.262,0.295,0.257
27,Sumatera Utara,0.319,0.3150,0.3176,0.3165,0.3161,0.3145,0.312,0.309,0.297
28,Tanjungbalai,0.3726,0.2784,0.3320,0.2678,0.2716,0.2477,0.245,0.238,0.236
29,Tapanuli Selatan,0.2729,0.2528,0.2727,0.2467,0.2022,0.2564,0.209,0.219,0.206
30,Tapanuli Tengah,0.3062,0.3058,0.3174,0.309,0.3350,0.2917,0.233,0.241,0.234
31,Tapanuli Utara,0.3087,0.3289,0.2819,0.3065,0.2867,0.2766,0.242,0.262,0.242
32,Tebing Tinggi,0.3577,0.3035,0.3396,0.3237,0.3337,0.3440,0.334,0.317,0.335
33,Toba,0.3077,0.2922,0.3279,0.2753,0.2903,0.2719,0.305,0.295,0.348